package clickhouseparser

import "niuma/pkg/sqllsp"

type builtinFn struct {
	Name   string
	Insert string
	Detail string
	Doc    string
}

func clickHouseBuiltins() []builtinFn {
	return []builtinFn{
		// —— 时间 / 日期 ——
		{Name: "now", Insert: "now()", Detail: "DateTime", Doc: "当前时间"},
		{Name: "today", Insert: "today()", Detail: "Date", Doc: "当前日期"},
		{Name: "yesterday", Insert: "yesterday()", Detail: "Date", Doc: "昨天"},
		{Name: "toDate", Insert: "toDate(${1:expr})", Detail: "Date", Doc: "转日期"},
		{Name: "toDate32", Insert: "toDate32(${1:expr})", Detail: "Date32", Doc: "转 Date32"},
		{Name: "toDateTime", Insert: "toDateTime(${1:expr})", Detail: "DateTime", Doc: "转日期时间"},
		{Name: "toDateTime64", Insert: "toDateTime64(${1:expr}, ${2:3})", Detail: "DateTime64", Doc: "转 DateTime64"},
		{Name: "toUnixTimestamp", Insert: "toUnixTimestamp(${1:expr})", Detail: "UInt32", Doc: "Unix 时间戳"},
		{Name: "fromUnixTimestamp", Insert: "fromUnixTimestamp(${1:ts})", Detail: "DateTime", Doc: "从时间戳转 DateTime"},
		{Name: "toStartOfDay", Insert: "toStartOfDay(${1:dt})", Detail: "DateTime", Doc: "日初"},
		{Name: "toStartOfHour", Insert: "toStartOfHour(${1:dt})", Detail: "DateTime", Doc: "整点"},
		{Name: "toStartOfMinute", Insert: "toStartOfMinute(${1:dt})", Detail: "DateTime", Doc: "整分"},
		{Name: "toStartOfWeek", Insert: "toStartOfWeek(${1:dt})", Detail: "Date", Doc: "周初"},
		{Name: "toStartOfMonth", Insert: "toStartOfMonth(${1:dt})", Detail: "Date", Doc: "月初"},
		{Name: "toStartOfQuarter", Insert: "toStartOfQuarter(${1:dt})", Detail: "Date", Doc: "季初"},
		{Name: "toStartOfYear", Insert: "toStartOfYear(${1:dt})", Detail: "Date", Doc: "年初"},
		{Name: "toMonday", Insert: "toMonday(${1:dt})", Detail: "Date", Doc: "本周一"},
		{Name: "toYYYYMM", Insert: "toYYYYMM(${1:dt})", Detail: "UInt32", Doc: "年月整数"},
		{Name: "toYYYYMMDD", Insert: "toYYYYMMDD(${1:dt})", Detail: "UInt32", Doc: "年月日整数"},
		{Name: "toYear", Insert: "toYear(${1:dt})", Detail: "UInt16", Doc: "年"},
		{Name: "toMonth", Insert: "toMonth(${1:dt})", Detail: "UInt8", Doc: "月"},
		{Name: "toDayOfMonth", Insert: "toDayOfMonth(${1:dt})", Detail: "UInt8", Doc: "日"},
		{Name: "toDayOfWeek", Insert: "toDayOfWeek(${1:dt})", Detail: "UInt8", Doc: "星期"},
		{Name: "toHour", Insert: "toHour(${1:dt})", Detail: "UInt8", Doc: "小时"},
		{Name: "toMinute", Insert: "toMinute(${1:dt})", Detail: "UInt8", Doc: "分钟"},
		{Name: "toSecond", Insert: "toSecond(${1:dt})", Detail: "UInt8", Doc: "秒"},
		{Name: "dateDiff", Insert: "dateDiff('${1:day}', ${2:a}, ${3:b})", Detail: "Int64", Doc: "日差"},
		{Name: "date_diff", Insert: "date_diff('${1:day}', ${2:a}, ${3:b})", Detail: "Int64", Doc: "日差（别名）"},
		{Name: "dateAdd", Insert: "dateAdd(${1:DAY}, ${2:n}, ${3:dt})", Detail: "Date/DateTime", Doc: "日期加"},
		{Name: "dateSub", Insert: "dateSub(${1:DAY}, ${2:n}, ${3:dt})", Detail: "Date/DateTime", Doc: "日期减"},
		{Name: "addDays", Insert: "addDays(${1:dt}, ${2:n})", Detail: "Date/DateTime", Doc: "加天"},
		{Name: "addMonths", Insert: "addMonths(${1:dt}, ${2:n})", Detail: "Date/DateTime", Doc: "加月"},
		{Name: "addYears", Insert: "addYears(${1:dt}, ${2:n})", Detail: "Date/DateTime", Doc: "加年"},
		{Name: "subtractDays", Insert: "subtractDays(${1:dt}, ${2:n})", Detail: "Date/DateTime", Doc: "减天"},
		{Name: "formatDateTime", Insert: "formatDateTime(${1:dt}, '${2:%Y-%m-%d %H:%M:%S}')", Detail: "String", Doc: "格式化时间"},
		{Name: "parseDateTimeBestEffort", Insert: "parseDateTimeBestEffort(${1:str})", Detail: "DateTime", Doc: "尽力解析时间"},
		{Name: "parseDateTimeBestEffortOrNull", Insert: "parseDateTimeBestEffortOrNull(${1:str})", Detail: "Nullable(DateTime)", Doc: "尽力解析或 NULL"},

		// —— 类型转换 ——
		{Name: "toString", Insert: "toString(${1:expr})", Detail: "String", Doc: "转字符串"},
		{Name: "toFixedString", Insert: "toFixedString(${1:expr}, ${2:n})", Detail: "FixedString", Doc: "定长字符串"},
		{Name: "toInt8", Insert: "toInt8(${1:expr})", Detail: "Int8", Doc: "转 Int8"},
		{Name: "toInt16", Insert: "toInt16(${1:expr})", Detail: "Int16", Doc: "转 Int16"},
		{Name: "toInt32", Insert: "toInt32(${1:expr})", Detail: "Int32", Doc: "转 Int32"},
		{Name: "toInt64", Insert: "toInt64(${1:expr})", Detail: "Int64", Doc: "转 Int64"},
		{Name: "toInt128", Insert: "toInt128(${1:expr})", Detail: "Int128", Doc: "转 Int128"},
		{Name: "toInt256", Insert: "toInt256(${1:expr})", Detail: "Int256", Doc: "转 Int256"},
		{Name: "toUInt8", Insert: "toUInt8(${1:expr})", Detail: "UInt8", Doc: "转 UInt8"},
		{Name: "toUInt16", Insert: "toUInt16(${1:expr})", Detail: "UInt16", Doc: "转 UInt16"},
		{Name: "toUInt32", Insert: "toUInt32(${1:expr})", Detail: "UInt32", Doc: "转 UInt32"},
		{Name: "toUInt64", Insert: "toUInt64(${1:expr})", Detail: "UInt64", Doc: "转 UInt64"},
		{Name: "toFloat32", Insert: "toFloat32(${1:expr})", Detail: "Float32", Doc: "转 Float32"},
		{Name: "toFloat64", Insert: "toFloat64(${1:expr})", Detail: "Float64", Doc: "转 Float64"},
		{Name: "toDecimal64", Insert: "toDecimal64(${1:expr}, ${2:scale})", Detail: "Decimal64", Doc: "转 Decimal64"},
		{Name: "toUUID", Insert: "toUUID(${1:expr})", Detail: "UUID", Doc: "转 UUID"},
		{Name: "toIPv4", Insert: "toIPv4(${1:expr})", Detail: "IPv4", Doc: "转 IPv4"},
		{Name: "toIPv6", Insert: "toIPv6(${1:expr})", Detail: "IPv6", Doc: "转 IPv6"},
		{Name: "cast", Insert: "cast(${1:expr} AS ${2:type})", Detail: "any", Doc: "类型转换"},
		{Name: "accurateCast", Insert: "accurateCast(${1:expr}, '${2:type}')", Detail: "any", Doc: "精确转换"},
		{Name: "accurateCastOrNull", Insert: "accurateCastOrNull(${1:expr}, '${2:type}')", Detail: "Nullable", Doc: "精确转换或 NULL"},
		{Name: "reinterpretAsString", Insert: "reinterpretAsString(${1:expr})", Detail: "String", Doc: "按字节重解释为字符串"},
		{Name: "toTypeName", Insert: "toTypeName(${1:expr})", Detail: "String", Doc: "表达式类型名"},

		// —— 条件 / 空值 ——
		{Name: "if", Insert: "if(${1:cond}, ${2:then}, ${3:else})", Detail: "any", Doc: "条件"},
		{Name: "multiIf", Insert: "multiIf(${1:c1}, ${2:v1}, ${3:default})", Detail: "any", Doc: "多条件"},
		{Name: "coalesce", Insert: "coalesce(${1:a}, ${2:b})", Detail: "any", Doc: "首个非 NULL"},
		{Name: "ifNull", Insert: "ifNull(${1:a}, ${2:b})", Detail: "any", Doc: "NULL 则替换"},
		{Name: "nullIf", Insert: "nullIf(${1:a}, ${2:b})", Detail: "any", Doc: "相等则 NULL"},
		{Name: "assumeNotNull", Insert: "assumeNotNull(${1:expr})", Detail: "any", Doc: "假定非 NULL"},
		{Name: "isNull", Insert: "isNull(${1:expr})", Detail: "UInt8", Doc: "是否 NULL"},
		{Name: "isNotNull", Insert: "isNotNull(${1:expr})", Detail: "UInt8", Doc: "是否非 NULL"},
		{Name: "transform", Insert: "transform(${1:expr}, [${2:from}], [${3:to}], ${4:default})", Detail: "any", Doc: "映射转换"},

		// —— 聚合 ——
		{Name: "count", Insert: "count(${1:*})", Detail: "aggregate", Doc: "计数"},
		{Name: "countIf", Insert: "countIf(${1:cond})", Detail: "aggregate", Doc: "条件计数"},
		{Name: "sum", Insert: "sum(${1:expr})", Detail: "aggregate", Doc: "求和"},
		{Name: "sumIf", Insert: "sumIf(${1:expr}, ${2:cond})", Detail: "aggregate", Doc: "条件求和"},
		{Name: "avg", Insert: "avg(${1:expr})", Detail: "aggregate", Doc: "平均"},
		{Name: "avgIf", Insert: "avgIf(${1:expr}, ${2:cond})", Detail: "aggregate", Doc: "条件平均"},
		{Name: "min", Insert: "min(${1:expr})", Detail: "aggregate", Doc: "最小"},
		{Name: "max", Insert: "max(${1:expr})", Detail: "aggregate", Doc: "最大"},
		{Name: "any", Insert: "any(${1:expr})", Detail: "aggregate", Doc: "任意值"},
		{Name: "anyLast", Insert: "anyLast(${1:expr})", Detail: "aggregate", Doc: "最后一个值"},
		{Name: "argMin", Insert: "argMin(${1:arg}, ${2:val})", Detail: "aggregate", Doc: "最小值对应参数"},
		{Name: "argMax", Insert: "argMax(${1:arg}, ${2:val})", Detail: "aggregate", Doc: "最大值对应参数"},
		{Name: "uniq", Insert: "uniq(${1:expr})", Detail: "aggregate", Doc: "近似去重"},
		{Name: "uniqExact", Insert: "uniqExact(${1:expr})", Detail: "aggregate", Doc: "精确去重"},
		{Name: "uniqCombined", Insert: "uniqCombined(${1:expr})", Detail: "aggregate", Doc: "组合去重"},
		{Name: "uniqHLL12", Insert: "uniqHLL12(${1:expr})", Detail: "aggregate", Doc: "HLL 去重"},
		{Name: "groupArray", Insert: "groupArray(${1:expr})", Detail: "aggregate", Doc: "聚合为数组"},
		{Name: "groupArrayIf", Insert: "groupArrayIf(${1:expr}, ${2:cond})", Detail: "aggregate", Doc: "条件聚合数组"},
		{Name: "groupUniqArray", Insert: "groupUniqArray(${1:expr})", Detail: "aggregate", Doc: "去重数组"},
		{Name: "groupBitmap", Insert: "groupBitmap(${1:expr})", Detail: "aggregate", Doc: "位图聚合"},
		{Name: "quantile", Insert: "quantile(${1:level})(${2:expr})", Detail: "aggregate", Doc: "分位数"},
		{Name: "quantiles", Insert: "quantiles(${1:0.5}, ${2:0.9})(${3:expr})", Detail: "aggregate", Doc: "多分位数"},
		{Name: "median", Insert: "median(${1:expr})", Detail: "aggregate", Doc: "中位数"},
		{Name: "stddevPop", Insert: "stddevPop(${1:expr})", Detail: "aggregate", Doc: "总体标准差"},
		{Name: "stddevSamp", Insert: "stddevSamp(${1:expr})", Detail: "aggregate", Doc: "样本标准差"},
		{Name: "varPop", Insert: "varPop(${1:expr})", Detail: "aggregate", Doc: "总体方差"},
		{Name: "varSamp", Insert: "varSamp(${1:expr})", Detail: "aggregate", Doc: "样本方差"},
		{Name: "corr", Insert: "corr(${1:x}, ${2:y})", Detail: "aggregate", Doc: "相关系数"},
		{Name: "covarPop", Insert: "covarPop(${1:x}, ${2:y})", Detail: "aggregate", Doc: "总体协方差"},
		{Name: "topK", Insert: "topK(${1:k})(${2:expr})", Detail: "aggregate", Doc: "高频 TopK"},
		{Name: "topKWeighted", Insert: "topKWeighted(${1:k})(${2:expr}, ${3:weight})", Detail: "aggregate", Doc: "加权 TopK"},

		// —— 字符串 ——
		{Name: "length", Insert: "length(${1:expr})", Detail: "UInt64", Doc: "长度（字节/元素）"},
		{Name: "lengthUTF8", Insert: "lengthUTF8(${1:str})", Detail: "UInt64", Doc: "UTF-8 字符数"},
		{Name: "empty", Insert: "empty(${1:expr})", Detail: "UInt8", Doc: "是否为空"},
		{Name: "notEmpty", Insert: "notEmpty(${1:expr})", Detail: "UInt8", Doc: "是否非空"},
		{Name: "lower", Insert: "lower(${1:str})", Detail: "String", Doc: "小写"},
		{Name: "upper", Insert: "upper(${1:str})", Detail: "String", Doc: "大写"},
		{Name: "lowerUTF8", Insert: "lowerUTF8(${1:str})", Detail: "String", Doc: "UTF-8 小写"},
		{Name: "upperUTF8", Insert: "upperUTF8(${1:str})", Detail: "String", Doc: "UTF-8 大写"},
		{Name: "substring", Insert: "substring(${1:str}, ${2:pos}, ${3:len})", Detail: "String", Doc: "子串"},
		{Name: "substringUTF8", Insert: "substringUTF8(${1:str}, ${2:pos}, ${3:len})", Detail: "String", Doc: "UTF-8 子串"},
		{Name: "left", Insert: "left(${1:str}, ${2:n})", Detail: "String", Doc: "左截取"},
		{Name: "right", Insert: "right(${1:str}, ${2:n})", Detail: "String", Doc: "右截取"},
		{Name: "concat", Insert: "concat(${1:a}, ${2:b})", Detail: "String", Doc: "连接"},
		{Name: "concatWithSeparator", Insert: "concatWithSeparator('${1:,}', ${2:a}, ${3:b})", Detail: "String", Doc: "分隔连接"},
		{Name: "replaceAll", Insert: "replaceAll(${1:hay}, ${2:needle}, ${3:repl})", Detail: "String", Doc: "全部替换"},
		{Name: "replaceOne", Insert: "replaceOne(${1:hay}, ${2:needle}, ${3:repl})", Detail: "String", Doc: "替换一次"},
		{Name: "replaceRegexpAll", Insert: "replaceRegexpAll(${1:hay}, ${2:pat}, ${3:repl})", Detail: "String", Doc: "正则全部替换"},
		{Name: "replaceRegexpOne", Insert: "replaceRegexpOne(${1:hay}, ${2:pat}, ${3:repl})", Detail: "String", Doc: "正则替换一次"},
		{Name: "trim", Insert: "trim(${1:str})", Detail: "String", Doc: "去空白"},
		{Name: "trimLeft", Insert: "trimLeft(${1:str})", Detail: "String", Doc: "去左空白"},
		{Name: "trimRight", Insert: "trimRight(${1:str})", Detail: "String", Doc: "去右空白"},
		{Name: "splitByChar", Insert: "splitByChar('${1:,}', ${2:str})", Detail: "Array(String)", Doc: "按字符拆分"},
		{Name: "splitByString", Insert: "splitByString('${1:,}', ${2:str})", Detail: "Array(String)", Doc: "按字符串拆分"},
		{Name: "arrayStringConcat", Insert: "arrayStringConcat(${1:arr}, '${2:,}')", Detail: "String", Doc: "数组拼串"},
		{Name: "position", Insert: "position(${1:hay}, ${2:needle})", Detail: "UInt64", Doc: "子串位置"},
		{Name: "positionCaseInsensitive", Insert: "positionCaseInsensitive(${1:hay}, ${2:needle})", Detail: "UInt64", Doc: "忽略大小写位置"},
		{Name: "startsWith", Insert: "startsWith(${1:str}, ${2:prefix})", Detail: "UInt8", Doc: "前缀匹配"},
		{Name: "endsWith", Insert: "endsWith(${1:str}, ${2:suffix})", Detail: "UInt8", Doc: "后缀匹配"},
		{Name: "match", Insert: "match(${1:str}, ${2:pat})", Detail: "UInt8", Doc: "正则匹配"},
		{Name: "multiMatchAny", Insert: "multiMatchAny(${1:str}, [${2:pats}])", Detail: "UInt8", Doc: "多模式匹配"},
		{Name: "extractAll", Insert: "extractAll(${1:str}, ${2:pat})", Detail: "Array(String)", Doc: "提取全部匹配"},
		{Name: "extractTextFromHTML", Insert: "extractTextFromHTML(${1:html})", Detail: "String", Doc: "HTML 抽文本"},
		{Name: "base64Encode", Insert: "base64Encode(${1:str})", Detail: "String", Doc: "Base64 编码"},
		{Name: "base64Decode", Insert: "base64Decode(${1:str})", Detail: "String", Doc: "Base64 解码"},
		{Name: "hex", Insert: "hex(${1:expr})", Detail: "String", Doc: "十六进制"},
		{Name: "unhex", Insert: "unhex(${1:str})", Detail: "String", Doc: "反十六进制"},
		{Name: "CRC32", Insert: "CRC32(${1:str})", Detail: "UInt32", Doc: "CRC32"},
		{Name: "MD5", Insert: "MD5(${1:str})", Detail: "FixedString(16)", Doc: "MD5"},
		{Name: "SHA256", Insert: "SHA256(${1:str})", Detail: "FixedString(32)", Doc: "SHA256"},

		// —— 数组 / Map / Tuple ——
		{Name: "arrayJoin", Insert: "arrayJoin(${1:arr})", Detail: "any", Doc: "展开数组"},
		{Name: "array", Insert: "array(${1:a}, ${2:b})", Detail: "Array", Doc: "构造数组"},
		{Name: "arrayElement", Insert: "arrayElement(${1:arr}, ${2:i})", Detail: "any", Doc: "数组元素"},
		{Name: "has", Insert: "has(${1:arr}, ${2:v})", Detail: "UInt8", Doc: "数组包含"},
		{Name: "hasAny", Insert: "hasAny(${1:arr}, ${2:vals})", Detail: "UInt8", Doc: "包含任一"},
		{Name: "hasAll", Insert: "hasAll(${1:arr}, ${2:vals})", Detail: "UInt8", Doc: "包含全部"},
		{Name: "indexOf", Insert: "indexOf(${1:arr}, ${2:v})", Detail: "UInt64", Doc: "元素下标"},
		{Name: "arrayCount", Insert: "arrayCount(x -> ${1:cond}, ${2:arr})", Detail: "UInt64", Doc: "数组条件计数"},
		{Name: "arrayFilter", Insert: "arrayFilter(x -> ${1:cond}, ${2:arr})", Detail: "Array", Doc: "数组过滤"},
		{Name: "arrayMap", Insert: "arrayMap(x -> ${1:expr}, ${2:arr})", Detail: "Array", Doc: "数组映射"},
		{Name: "arrayExists", Insert: "arrayExists(x -> ${1:cond}, ${2:arr})", Detail: "UInt8", Doc: "数组存在"},
		{Name: "arrayAll", Insert: "arrayAll(x -> ${1:cond}, ${2:arr})", Detail: "UInt8", Doc: "数组全满足"},
		{Name: "arraySum", Insert: "arraySum(${1:arr})", Detail: "number", Doc: "数组求和"},
		{Name: "arrayAvg", Insert: "arrayAvg(${1:arr})", Detail: "Float64", Doc: "数组平均"},
		{Name: "arrayMin", Insert: "arrayMin(${1:arr})", Detail: "any", Doc: "数组最小"},
		{Name: "arrayMax", Insert: "arrayMax(${1:arr})", Detail: "any", Doc: "数组最大"},
		{Name: "arrayDistinct", Insert: "arrayDistinct(${1:arr})", Detail: "Array", Doc: "数组去重"},
		{Name: "arraySort", Insert: "arraySort(${1:arr})", Detail: "Array", Doc: "数组排序"},
		{Name: "arrayReverse", Insert: "arrayReverse(${1:arr})", Detail: "Array", Doc: "数组反转"},
		{Name: "arrayFlatten", Insert: "arrayFlatten(${1:arr})", Detail: "Array", Doc: "数组展平"},
		{Name: "arrayConcat", Insert: "arrayConcat(${1:a}, ${2:b})", Detail: "Array", Doc: "数组合并"},
		{Name: "arraySlice", Insert: "arraySlice(${1:arr}, ${2:offset}, ${3:len})", Detail: "Array", Doc: "数组切片"},
		{Name: "arrayPushBack", Insert: "arrayPushBack(${1:arr}, ${2:v})", Detail: "Array", Doc: "尾部追加"},
		{Name: "arrayPushFront", Insert: "arrayPushFront(${1:arr}, ${2:v})", Detail: "Array", Doc: "头部追加"},
		{Name: "arrayPopBack", Insert: "arrayPopBack(${1:arr})", Detail: "Array", Doc: "弹出尾部"},
		{Name: "arrayPopFront", Insert: "arrayPopFront(${1:arr})", Detail: "Array", Doc: "弹出头部"},
		{Name: "range", Insert: "range(${1:n})", Detail: "Array(UInt)", Doc: "生成序列"},
		{Name: "map", Insert: "map(${1:k1}, ${2:v1})", Detail: "Map", Doc: "构造 Map"},
		{Name: "mapKeys", Insert: "mapKeys(${1:m})", Detail: "Array", Doc: "Map 键"},
		{Name: "mapValues", Insert: "mapValues(${1:m})", Detail: "Array", Doc: "Map 值"},
		{Name: "mapContains", Insert: "mapContains(${1:m}, ${2:key})", Detail: "UInt8", Doc: "Map 含键"},
		{Name: "tuple", Insert: "tuple(${1:a}, ${2:b})", Detail: "Tuple", Doc: "构造元组"},
		{Name: "tupleElement", Insert: "tupleElement(${1:t}, ${2:i})", Detail: "any", Doc: "元组元素"},
		{Name: "untuple", Insert: "untuple(${1:t})", Detail: "columns", Doc: "展开元组为列"},

		// —— 数学 ——
		{Name: "abs", Insert: "abs(${1:n})", Detail: "number", Doc: "绝对值"},
		{Name: "round", Insert: "round(${1:n}, ${2:scale})", Detail: "number", Doc: "四舍五入"},
		{Name: "floor", Insert: "floor(${1:n})", Detail: "number", Doc: "向下取整"},
		{Name: "ceil", Insert: "ceil(${1:n})", Detail: "number", Doc: "向上取整"},
		{Name: "trunc", Insert: "trunc(${1:n})", Detail: "number", Doc: "截断"},
		{Name: "greatest", Insert: "greatest(${1:a}, ${2:b})", Detail: "any", Doc: "最大"},
		{Name: "least", Insert: "least(${1:a}, ${2:b})", Detail: "any", Doc: "最小"},
		{Name: "pow", Insert: "pow(${1:x}, ${2:y})", Detail: "Float64", Doc: "幂"},
		{Name: "sqrt", Insert: "sqrt(${1:n})", Detail: "Float64", Doc: "平方根"},
		{Name: "cbrt", Insert: "cbrt(${1:n})", Detail: "Float64", Doc: "立方根"},
		{Name: "exp", Insert: "exp(${1:n})", Detail: "Float64", Doc: "e 的幂"},
		{Name: "log", Insert: "log(${1:n})", Detail: "Float64", Doc: "自然对数"},
		{Name: "log2", Insert: "log2(${1:n})", Detail: "Float64", Doc: "以 2 为底对数"},
		{Name: "log10", Insert: "log10(${1:n})", Detail: "Float64", Doc: "以 10 为底对数"},
		{Name: "sin", Insert: "sin(${1:n})", Detail: "Float64", Doc: "正弦"},
		{Name: "cos", Insert: "cos(${1:n})", Detail: "Float64", Doc: "余弦"},
		{Name: "tan", Insert: "tan(${1:n})", Detail: "Float64", Doc: "正切"},
		{Name: "pi", Insert: "pi()", Detail: "Float64", Doc: "圆周率"},
		{Name: "e", Insert: "e()", Detail: "Float64", Doc: "自然常数"},
		{Name: "sign", Insert: "sign(${1:n})", Detail: "Int8", Doc: "符号"},
		{Name: "gcd", Insert: "gcd(${1:a}, ${2:b})", Detail: "integer", Doc: "最大公约数"},
		{Name: "lcm", Insert: "lcm(${1:a}, ${2:b})", Detail: "integer", Doc: "最小公倍数"},
		{Name: "modulo", Insert: "modulo(${1:a}, ${2:b})", Detail: "number", Doc: "取模"},
		{Name: "intDiv", Insert: "intDiv(${1:a}, ${2:b})", Detail: "integer", Doc: "整除"},
		{Name: "intDivOrZero", Insert: "intDivOrZero(${1:a}, ${2:b})", Detail: "integer", Doc: "整除（除零为 0）"},

		// —— 哈希 / UUID / 随机 ——
		{Name: "cityHash64", Insert: "cityHash64(${1:expr})", Detail: "UInt64", Doc: "CityHash64"},
		{Name: "sipHash64", Insert: "sipHash64(${1:expr})", Detail: "UInt64", Doc: "SipHash64"},
		{Name: "sipHash128", Insert: "sipHash128(${1:expr})", Detail: "FixedString(16)", Doc: "SipHash128"},
		{Name: "farmHash64", Insert: "farmHash64(${1:expr})", Detail: "UInt64", Doc: "FarmHash64"},
		{Name: "javaHash", Insert: "javaHash(${1:str})", Detail: "Int32", Doc: "Java Hash"},
		{Name: "xxHash32", Insert: "xxHash32(${1:expr})", Detail: "UInt32", Doc: "xxHash32"},
		{Name: "xxHash64", Insert: "xxHash64(${1:expr})", Detail: "UInt64", Doc: "xxHash64"},
		{Name: "murmurHash2_32", Insert: "murmurHash2_32(${1:expr})", Detail: "UInt32", Doc: "MurmurHash2 32"},
		{Name: "murmurHash2_64", Insert: "murmurHash2_64(${1:expr})", Detail: "UInt64", Doc: "MurmurHash2 64"},
		{Name: "murmurHash3_32", Insert: "murmurHash3_32(${1:expr})", Detail: "UInt32", Doc: "MurmurHash3 32"},
		{Name: "murmurHash3_64", Insert: "murmurHash3_64(${1:expr})", Detail: "UInt64", Doc: "MurmurHash3 64"},
		{Name: "murmurHash3_128", Insert: "murmurHash3_128(${1:expr})", Detail: "FixedString(16)", Doc: "MurmurHash3 128"},
		{Name: "generateUUIDv4", Insert: "generateUUIDv4()", Detail: "UUID", Doc: "生成 UUID v4"},
		{Name: "generateUUIDv7", Insert: "generateUUIDv7()", Detail: "UUID", Doc: "生成 UUID v7"},
		{Name: "halfMD5", Insert: "halfMD5(${1:expr})", Detail: "UInt64", Doc: "MD5 半值"},
		{Name: "rand", Insert: "rand()", Detail: "UInt32", Doc: "随机 UInt32"},
		{Name: "rand64", Insert: "rand64()", Detail: "UInt64", Doc: "随机 UInt64"},
		{Name: "randConstant", Insert: "randConstant()", Detail: "UInt32", Doc: "常量随机"},
		{Name: "randomString", Insert: "randomString(${1:n})", Detail: "String", Doc: "随机字符串"},

		// —— JSON / URL ——
		{Name: "JSONExtract", Insert: "JSONExtract(${1:json}, ${2:path}, '${3:type}')", Detail: "any", Doc: "提取 JSON"},
		{Name: "JSONExtractString", Insert: "JSONExtractString(${1:json}, ${2:path})", Detail: "String", Doc: "提取 JSON 字符串"},
		{Name: "JSONExtractInt", Insert: "JSONExtractInt(${1:json}, ${2:path})", Detail: "Int64", Doc: "提取 JSON 整数"},
		{Name: "JSONExtractFloat", Insert: "JSONExtractFloat(${1:json}, ${2:path})", Detail: "Float64", Doc: "提取 JSON 浮点"},
		{Name: "JSONExtractBool", Insert: "JSONExtractBool(${1:json}, ${2:path})", Detail: "UInt8", Doc: "提取 JSON 布尔"},
		{Name: "JSONExtractRaw", Insert: "JSONExtractRaw(${1:json}, ${2:path})", Detail: "String", Doc: "提取 JSON 原始片段"},
		{Name: "JSONExtractKeys", Insert: "JSONExtractKeys(${1:json})", Detail: "Array(String)", Doc: "JSON 键列表"},
		{Name: "JSONHas", Insert: "JSONHas(${1:json}, ${2:path})", Detail: "UInt8", Doc: "JSON 路径是否存在"},
		{Name: "JSONLength", Insert: "JSONLength(${1:json}, ${2:path})", Detail: "UInt64", Doc: "JSON 数组/对象长度"},
		{Name: "JSONType", Insert: "JSONType(${1:json}, ${2:path})", Detail: "String", Doc: "JSON 类型"},
		{Name: "isValidJSON", Insert: "isValidJSON(${1:str})", Detail: "UInt8", Doc: "是否合法 JSON"},
		{Name: "visitParamExtractString", Insert: "visitParamExtractString(${1:params}, '${2:key}')", Detail: "String", Doc: "提取 visitParam 字符串"},
		{Name: "visitParamExtractInt", Insert: "visitParamExtractInt(${1:params}, '${2:key}')", Detail: "Int64", Doc: "提取 visitParam 整数"},
		{Name: "URLHash", Insert: "URLHash(${1:url})", Detail: "UInt64", Doc: "URL 哈希"},
		{Name: "domain", Insert: "domain(${1:url})", Detail: "String", Doc: "提取域名"},
		{Name: "domainWithoutWWW", Insert: "domainWithoutWWW(${1:url})", Detail: "String", Doc: "去 www 域名"},
		{Name: "topLevelDomain", Insert: "topLevelDomain(${1:url})", Detail: "String", Doc: "顶级域"},
		{Name: "protocol", Insert: "protocol(${1:url})", Detail: "String", Doc: "协议"},
		{Name: "path", Insert: "path(${1:url})", Detail: "String", Doc: "URL 路径"},
		{Name: "queryString", Insert: "queryString(${1:url})", Detail: "String", Doc: "查询串"},
		{Name: "cutQueryString", Insert: "cutQueryString(${1:url})", Detail: "String", Doc: "去掉查询串"},
		{Name: "decodeURLComponent", Insert: "decodeURLComponent(${1:str})", Detail: "String", Doc: "URL 解码"},
		{Name: "encodeURLComponent", Insert: "encodeURLComponent(${1:str})", Detail: "String", Doc: "URL 编码"},

		// —— 窗口 ——
		{Name: "row_number", Insert: "row_number() OVER (${1:ORDER BY col})", Detail: "window", Doc: "行号"},
		{Name: "rank", Insert: "rank() OVER (${1:ORDER BY col})", Detail: "window", Doc: "排名"},
		{Name: "dense_rank", Insert: "dense_rank() OVER (${1:ORDER BY col})", Detail: "window", Doc: "密集排名"},
		{Name: "percent_rank", Insert: "percent_rank() OVER (${1:ORDER BY col})", Detail: "window", Doc: "百分比排名"},
		{Name: "cume_dist", Insert: "cume_dist() OVER (${1:ORDER BY col})", Detail: "window", Doc: "累积分布"},
		{Name: "ntile", Insert: "ntile(${1:n}) OVER (${2:ORDER BY col})", Detail: "window", Doc: "分桶"},
		{Name: "lagInFrame", Insert: "lagInFrame(${1:expr}) OVER (${2:ORDER BY col})", Detail: "window", Doc: "上一行"},
		{Name: "leadInFrame", Insert: "leadInFrame(${1:expr}) OVER (${2:ORDER BY col})", Detail: "window", Doc: "下一行"},
		{Name: "first_value", Insert: "first_value(${1:expr}) OVER (${2:ORDER BY col})", Detail: "window", Doc: "窗口首值"},
		{Name: "last_value", Insert: "last_value(${1:expr}) OVER (${2:ORDER BY col})", Detail: "window", Doc: "窗口末值"},
		{Name: "nth_value", Insert: "nth_value(${1:expr}, ${2:n}) OVER (${3:ORDER BY col})", Detail: "window", Doc: "窗口第 n 值"},

		// —— 表函数 / 系统 ——
		{Name: "version", Insert: "version()", Detail: "String", Doc: "服务器版本"},
		{Name: "uptime", Insert: "uptime()", Detail: "UInt32", Doc: "运行秒数"},
		{Name: "currentDatabase", Insert: "currentDatabase()", Detail: "String", Doc: "当前库"},
		{Name: "currentUser", Insert: "currentUser()", Detail: "String", Doc: "当前用户"},
		{Name: "hostName", Insert: "hostName()", Detail: "String", Doc: "主机名"},
		{Name: "fqdn", Insert: "fqdn()", Detail: "String", Doc: "FQDN"},
		{Name: "getMacro", Insert: "getMacro('${1:name}')", Detail: "String", Doc: "读取宏"},
		{Name: "getSetting", Insert: "getSetting('${1:name}')", Detail: "any", Doc: "读取设置"},
		{Name: "formatReadableSize", Insert: "formatReadableSize(${1:bytes})", Detail: "String", Doc: "可读字节大小"},
		{Name: "formatReadableQuantity", Insert: "formatReadableQuantity(${1:n})", Detail: "String", Doc: "可读数量"},
		{Name: "formatReadableTimeDelta", Insert: "formatReadableTimeDelta(${1:sec})", Detail: "String", Doc: "可读时差"},
		{Name: "generateSeries", Insert: "generateSeries(${1:start}, ${2:end})", Detail: "table", Doc: "生成数列（表函数）"},
		{Name: "numbers", Insert: "numbers(${1:n})", Detail: "table", Doc: "生成数字表"},
		{Name: "numbers_mt", Insert: "numbers_mt(${1:n})", Detail: "table", Doc: "多线程数字表"},
		{Name: "remote", Insert: "remote('${1:host}', ${2:db.table})", Detail: "table", Doc: "远程表"},
		{Name: "remoteSecure", Insert: "remoteSecure('${1:host}', ${2:db.table})", Detail: "table", Doc: "安全远程表"},
		{Name: "cluster", Insert: "cluster('${1:name}', ${2:db.table})", Detail: "table", Doc: "集群表"},
		{Name: "clusterAllReplicas", Insert: "clusterAllReplicas('${1:name}', ${2:db.table})", Detail: "table", Doc: "集群全部副本"},
		{Name: "file", Insert: "file('${1:path}', '${2:Format}')", Detail: "table", Doc: "读文件"},
		{Name: "url", Insert: "url('${1:url}', '${2:Format}')", Detail: "table", Doc: "读 URL"},
		{Name: "s3", Insert: "s3('${1:url}', '${2:Format}')", Detail: "table", Doc: "读 S3"},
		{Name: "hdfs", Insert: "hdfs('${1:uri}', '${2:Format}')", Detail: "table", Doc: "读 HDFS"},
		{Name: "jdbc", Insert: "jdbc('${1:dsn}', '${2:db}', '${3:table}')", Detail: "table", Doc: "JDBC 表"},
		{Name: "odbc", Insert: "odbc('${1:dsn}', '${2:db}', '${3:table}')", Detail: "table", Doc: "ODBC 表"},
		{Name: "mysql", Insert: "mysql('${1:host:port}', '${2:db}', '${3:table}', '${4:user}', '${5:pass}')", Detail: "table", Doc: "MySQL 表"},
		{Name: "postgresql", Insert: "postgresql('${1:host:port}', '${2:db}', '${3:table}', '${4:user}', '${5:pass}')", Detail: "table", Doc: "PostgreSQL 表"},
		{Name: "input", Insert: "input('${1:structure}')", Detail: "table", Doc: "INSERT 输入结构"},
		{Name: "format", Insert: "format(${1:FormatName}, ${2:data})", Detail: "table", Doc: "按格式解析"},
		{Name: "values", Insert: "values(${1:structure})", Detail: "table", Doc: "VALUES 表函数"},
		{Name: "merge", Insert: "merge('${1:db}', '${2:regex}')", Detail: "table", Doc: "合并匹配表"},
		{Name: "dictionary", Insert: "dictionary('${1:name}')", Detail: "table", Doc: "字典表函数"},
		{Name: "dictGet", Insert: "dictGet('${1:dict}', '${2:attr}', ${3:id})", Detail: "any", Doc: "字典取值"},
		{Name: "dictGetOrDefault", Insert: "dictGetOrDefault('${1:dict}', '${2:attr}', ${3:id}, ${4:default})", Detail: "any", Doc: "字典取值或默认"},
		{Name: "dictHas", Insert: "dictHas('${1:dict}', ${2:id})", Detail: "UInt8", Doc: "字典是否有键"},
		{Name: "dictGetString", Insert: "dictGetString('${1:dict}', '${2:attr}', ${3:id})", Detail: "String", Doc: "字典取字符串"},
		{Name: "dictGetUInt64", Insert: "dictGetUInt64('${1:dict}', '${2:attr}', ${3:id})", Detail: "UInt64", Doc: "字典取 UInt64"},
		{Name: "dictGetInt64", Insert: "dictGetInt64('${1:dict}', '${2:attr}', ${3:id})", Detail: "Int64", Doc: "字典取 Int64"},
		{Name: "dictGetFloat64", Insert: "dictGetFloat64('${1:dict}', '${2:attr}', ${3:id})", Detail: "Float64", Doc: "字典取 Float64"},
		{Name: "dictGetDate", Insert: "dictGetDate('${1:dict}', '${2:attr}', ${3:id})", Detail: "Date", Doc: "字典取 Date"},
		{Name: "dictGetDateTime", Insert: "dictGetDateTime('${1:dict}', '${2:attr}', ${3:id})", Detail: "DateTime", Doc: "字典取 DateTime"},
	}
}

func clickHouseBuiltinFunctionNames() []string {
	fns := clickHouseBuiltins()
	out := make([]string, 0, len(fns))
	for _, f := range fns {
		out = append(out, f.Name)
	}
	return out
}

func clickHouseBuiltinFunctions() []sqllsp.CompletionItem {
	fns := clickHouseBuiltins()
	out := make([]sqllsp.CompletionItem, 0, len(fns))
	for _, f := range fns {
		insert := f.Insert
		if insert == "" {
			insert = f.Name + "()"
		}
		out = append(out, sqllsp.CompletionItem{
			Label:         f.Name,
			Kind:          3, // Function
			Detail:        f.Detail,
			InsertText:    insert,
			Documentation: f.Doc,
			SortText:      "2_" + f.Name,
		})
	}
	return out
}

func clickHouseCreateSnippets() []sqllsp.CompletionItem {
	return []sqllsp.CompletionItem{
		{
			Label:      "CREATE TABLE",
			Kind:       15, // Snippet
			Detail:     "snippet",
			InsertText: "CREATE TABLE IF NOT EXISTS ${1:db}.${2:name}\n(\n  ${3:id} UInt64,\n  ${4:dt} DateTime\n)\nENGINE = MergeTree\nORDER BY (${3:id})",
			SortText:   "0_create_table",
		},
		{
			Label:      "CREATE VIEW",
			Kind:       15,
			Detail:     "snippet",
			InsertText: "CREATE VIEW IF NOT EXISTS ${1:db}.${2:name} AS\nSELECT ${3:*} FROM ${4:db.table}",
			SortText:   "0_create_view",
		},
		{
			Label:      "CREATE MATERIALIZED VIEW",
			Kind:       15,
			Detail:     "snippet",
			InsertText: "CREATE MATERIALIZED VIEW IF NOT EXISTS ${1:db}.${2:name}\nENGINE = MergeTree ORDER BY ${3:tuple()}\nAS SELECT ${4:*} FROM ${5:db.src}",
			SortText:   "0_create_mv",
		},
		{
			Label:      "CREATE DICTIONARY",
			Kind:       15,
			Detail:     "snippet",
			InsertText: "CREATE DICTIONARY IF NOT EXISTS ${1:db}.${2:name}\n(\n  ${3:id} UInt64,\n  ${4:val} String\n)\nPRIMARY KEY ${3:id}\nSOURCE(CLICKHOUSE(TABLE '${5:src}'))\nLAYOUT(HASHED())\nLIFETIME(MIN 0 MAX 3600)",
			SortText:   "0_create_dict",
		},
		{
			Label:      "ALTER TABLE ADD COLUMN",
			Kind:       15,
			Detail:     "snippet",
			InsertText: "ALTER TABLE ${1:db.table} ADD COLUMN IF NOT EXISTS ${2:col} ${3:String}",
			SortText:   "0_alter_add",
		},
		{
			Label:      "OPTIMIZE TABLE",
			Kind:       15,
			Detail:     "snippet",
			InsertText: "OPTIMIZE TABLE ${1:db.table} FINAL",
			SortText:   "0_optimize",
		},
	}
}
