/** 判断 FTP Bridge 错误是否像物理连接已断开（可尝试自动重连）。 */
export function isFtpConnectionError(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err ?? '')
  const lower = message.toLowerCase()
  return (
    lower.includes('connection was aborted')
    || lower.includes('connection reset')
    || lower.includes('connection refused')
    || lower.includes('connection lost')
    || lower.includes('broken pipe')
    || lower.includes('eof')
    || lower.includes('use of closed network connection')
    || lower.includes('wsasend')
    || lower.includes('wsarecv')
    || lower.includes('i/o timeout')
    || lower.includes('idle timeout')
    || lower.includes('closing control')
    || lower.includes('not connected')
    || lower.includes('session not found')
    || lower.includes('421')
    || lower.includes('426')
    || lower.includes('operation was canceled')
    || lower.includes('operation was cancelled')
  )
}
