package sqlserverparser

// sqlServerKeywords 补全 / Monarch 单源（T-SQL 常用集，对标 SSMS / Navicat / DBeaver）。
var sqlServerKeywords = []string{
	// —— DML / 查询 ——
	"SELECT", "FROM", "WHERE", "HAVING", "GROUP", "ORDER", "BY", "ASC", "DESC",
	"INSERT", "INTO", "VALUES", "UPDATE", "DELETE", "MERGE", "OUTPUT", "INSERTED", "DELETED",
	"WITH", "RECURSIVE", "DISTINCT", "ALL", "TOP", "PERCENT", "TIES",
	"UNION", "INTERSECT", "EXCEPT", "APPLY", "CROSS", "OUTER",
	"JOIN", "LEFT", "RIGHT", "INNER", "FULL", "ON", "USING",
	"CASE", "WHEN", "THEN", "ELSE", "END",
	"AND", "OR", "NOT", "IN", "EXISTS", "BETWEEN", "LIKE", "IS", "NULL",
	"AS", "CAST", "CONVERT", "TRY_CAST", "TRY_CONVERT", "COALESCE", "NULLIF", "IIF",
	"OVER", "PARTITION", "ROWS", "RANGE", "UNBOUNDED", "PRECEDING", "FOLLOWING",
	"CURRENT", "ROW", "WINDOW",
	"OFFSET", "FETCH", "NEXT", "ONLY", "FIRST", "LAST",
	"PIVOT", "UNPIVOT", "FOR", "XML", "PATH", "ELEMENTS", "RAW", "AUTO", "EXPLICIT",
	"OPTION", "HASH", "LOOP", "MERGE", "FORCE", "ORDER", "RECOMPILE", "MAXDOP",
	"TABLESAMPLE", "SYSTEM", "REPEATABLE",
	"INTO", "OPENQUERY", "OPENROWSET", "OPENDATASOURCE", "OPENXML",

	// —— 过程控制 / 批 ——
	"BEGIN", "END", "TRAN", "TRANSACTION", "COMMIT", "ROLLBACK", "SAVE", "SAVETRAN",
	"IF", "ELSE", "WHILE", "BREAK", "CONTINUE", "GOTO", "RETURN", "WAITFOR", "DELAY", "TIME",
	"TRY", "CATCH", "THROW", "RAISERROR",
	"DECLARE", "SET", "EXEC", "EXECUTE", "GO",
	"PRINT", "USE", "KILL",

	// —— DDL / 对象 ——
	"CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME",
	"TABLE", "VIEW", "INDEX", "PROCEDURE", "PROC", "FUNCTION", "TRIGGER", "SEQUENCE",
	"SCHEMA", "DATABASE", "TYPE", "SYNONYM", "DEFAULT", "RULE", "CONSTRAINT",
	"PRIMARY", "KEY", "UNIQUE", "FOREIGN", "REFERENCES", "CHECK", "CLUSTERED", "NONCLUSTERED",
	"IDENTITY", "ROWGUIDCOL", "SPARSE", "PERSISTED", "COMPUTED",
	"ADD", "MODIFY", "COLUMN", "COLUMNS", "WITH", "NOCHECK", "CHECK",
	"ENABLE", "DISABLE", "REBUILD", "REORGANIZE", "STATISTICS", "UPDATE",
	"INCLUDE", "FILLFACTOR", "PAD_INDEX", "ONLINE", "RESUMABLE",
	"TEMPORARY", "TEMP", "VARIABLE", "TABLE",
	"INSTEAD", "OF", "AFTER", "FOR", "AS",
	"RETURNS", "RETURN", "TABLE", "INLINE", "SCHEMABINDING", "ENCRYPTION",
	"EXTERNAL", "FILE", "FILEGROUP", "FILESTREAM", "MEMORY_OPTIMIZED", "DURABILITY",
	"PARTITION", "SCHEME", "RANGE", "LEFT", "RIGHT", "BOUNDARY",
	"COLLATE", "DATABASE_DEFAULT",

	// —— 权限 / 安全 ——
	"GRANT", "REVOKE", "DENY", "TO", "FROM", "CASCADE", "AS",
	"ROLE", "USER", "LOGIN", "PASSWORD", "AUTHORIZATION", "OWNER",
	"SECURITY", "POLICY", "PREDICATE", "FILTER", "BLOCK",

	// —— 元数据 / 展示 ——
	"SHOW", "DESCRIBE", "DESC", "EXPLAIN", "DBCC", "CHECKPOINT", "BACKUP", "RESTORE",
	"SHUTDOWN", "RECONFIGURE",

	// —— 常用数据类型 ——
	"BIGINT", "INT", "INTEGER", "SMALLINT", "TINYINT", "BIT",
	"DECIMAL", "NUMERIC", "MONEY", "SMALLMONEY", "FLOAT", "REAL",
	"DATE", "TIME", "DATETIME", "DATETIME2", "SMALLDATETIME", "DATETIMEOFFSET",
	"CHAR", "VARCHAR", "NCHAR", "NVARCHAR", "TEXT", "NTEXT",
	"BINARY", "VARBINARY", "IMAGE", "UNIQUEIDENTIFIER", "XML", "SQL_VARIANT",
	"HIERARCHYID", "GEOMETRY", "GEOGRAPHY", "SYSNAME", "TIMESTAMP", "ROWVERSION",
	"JSON",

	// —— 其它常用词 ——
	"TRUE", "FALSE", "UNKNOWN", "SOME", "ANY", "ESCAPE",
	"COLLATION", "CONTAINS", "FREETEXT", "CONTAINSTABLE", "FREETEXTTABLE",
	"NOLOCK", "READUNCOMMITTED", "READCOMMITTED", "REPEATABLEREAD", "SERIALIZABLE",
	"SNAPSHOT", "READPAST", "UPDLOCK", "XLOCK", "ROWLOCK", "PAGLOCK", "TABLOCK", "TABLOCKX",
	"HOLDLOCK", "NOWAIT", "READCOMMITTEDLOCK",
	"OUTPUT", "INSERTED", "DELETED",
	"YEAR", "QUARTER", "MONTH", "DAY", "WEEK", "HOUR", "MINUTE", "SECOND", "MILLISECOND", "MICROSECOND", "NANOSECOND",
	"TZOFFSET", "ISO_WEEK",
}
