package sqliteparser

// sqliteKeywords 补全 / Monarch 单源（SQLite 3 核心 + 常用亲和类型）。
var sqliteKeywords = []string{
	"SELECT", "FROM", "WHERE", "HAVING", "GROUP", "ORDER", "BY", "LIMIT", "OFFSET",
	"INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE", "REPLACE",
	"WITH", "RECURSIVE", "DISTINCT", "ALL", "AS", "UNION", "INTERSECT", "EXCEPT",
	"JOIN", "LEFT", "RIGHT", "INNER", "OUTER", "FULL", "CROSS", "NATURAL", "ON", "USING",
	"CASE", "WHEN", "THEN", "ELSE", "END",
	"AND", "OR", "NOT", "IN", "EXISTS", "BETWEEN", "LIKE", "GLOB", "REGEXP", "MATCH", "IS", "NULL",
	"ISNULL", "NOTNULL", "TRUE", "FALSE", "CAST", "COLLATE", "ESCAPE",
	"CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP",

	"CREATE", "DROP", "ALTER", "RENAME", "ADD", "COLUMN", "TABLE", "VIEW", "INDEX", "TRIGGER",
	"TEMPORARY", "TEMP", "IF", "UNIQUE", "PRIMARY", "KEY", "FOREIGN", "REFERENCES",
	"CONSTRAINT", "CHECK", "DEFAULT", "GENERATED", "ALWAYS", "STORED", "VIRTUAL",
	"AUTOINCREMENT", "WITHOUT", "ROWID", "STRICT", "ASC", "DESC",
	"BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT", "RELEASE", "TRANSACTION",
	"ATTACH", "DETACH", "DATABASE", "PRAGMA", "VACUUM", "ANALYZE", "REINDEX", "EXPLAIN", "QUERY", "PLAN",
	"CONFLICT", "ABORT", "FAIL", "IGNORE", "NOTHING", "RAISE",

	"BEFORE", "AFTER", "INSTEAD", "OF", "FOR", "EACH", "ROW", "WHEN",
	"CASCADE", "RESTRICT", "NO", "ACTION", "SET", "DEFERRED", "IMMEDIATE", "EXCLUSIVE",
	"DEFERRABLE", "INITIALLY",

	"INTEGER", "INT", "TINYINT", "SMALLINT", "MEDIUMINT", "BIGINT", "UNSIGNED", "BIG",
	"TEXT", "CLOB", "BLOB", "REAL", "DOUBLE", "PRECISION", "FLOAT", "NUMERIC", "DECIMAL",
	"BOOLEAN", "DATE", "DATETIME", "TIMESTAMP", "VARCHAR", "CHAR", "NVARCHAR",

	"OVER", "PARTITION", "ROWS", "RANGE", "UNBOUNDED", "PRECEDING", "FOLLOWING", "CURRENT",
	"FILTER", "EXCLUDE", "OTHERS", "TIES", "GROUPS",
	"WINDOW", "RETURNING",
}
