#Requires -Version 5.1
<#
.SYNOPSIS
  将 pack:win 组装的绿色目录打成 Windows 安装程序（Setup.exe）。

.NOTES
  使用 Inno Setup 6（可免费商用，见 https://jrsoftware.org/files/is/license.txt）。
  安装：winget install --id JRSoftware.InnoSetup -e
#>
param(
    [ValidateSet('windows')]
    [string]$Platform = 'windows',

    [ValidateSet('x64', 'arm64')]
    [string]$Arch = 'x64',

    [string]$InputDir = '',
    [string]$OutputDir = '',
    [string]$Publisher = '',
    [string]$AppUrl = ''
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
. (Join-Path $Root 'scripts\shared\lib\matrix.ps1')

if (-not $InputDir) {
    $InputDir = Get-DefaultPackOutputDir -RepoRoot $Root -Platform $Platform -Arch $Arch -Format 'dir'
}
if (-not $OutputDir) {
    $OutputDir = Get-DefaultPackOutputDir -RepoRoot $Root -Platform $Platform -Arch $Arch -Format 'setup'
}

$AppExe = Join-Path $InputDir 'niuma.exe'
if (-not (Test-Path $AppExe)) {
    throw "Packaged app not found: $AppExe. Run: pnpm pack:win"
}

function Write-Step {
    param([string]$Message)
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Find-InnoSetupCompiler {
    $cmd = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }

    foreach ($path in @(
            "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
            "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
        )) {
        if (Test-Path $path) { return $path }
    }
    return $null
}

function Format-InnoVersion {
    param([string]$Version)
    $parts = $Version.Split('.')
    while ($parts.Count -lt 4) {
        $parts += '0'
    }
    return ($parts[0..3] -join '.')
}

function Escape-InnoPath {
    param([string]$Path)
    return ($Path -replace '\\', '/')
}

function Get-FileSha256Hex {
    param([string]$Path)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $stream = [System.IO.File]::OpenRead($Path)
    try {
        $hash = $sha.ComputeHash($stream)
        return [System.BitConverter]::ToString($hash).Replace('-', '').ToLowerInvariant()
    } finally {
        $stream.Dispose()
        $sha.Dispose()
    }
}

. (Join-Path $Root 'scripts\shared\lib\version.ps1')
$pkgJson = Get-Content (Join-Path $Root 'package.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$buildInfo = Get-BuildInfo -RepoRoot $Root
$AppVersion = [string]$pkgJson.version
$buildNumber = 0
if ($buildInfo.PSObject.Properties['buildNumber']) {
    [void][int]::TryParse([string]$buildInfo.buildNumber, [ref]$buildNumber)
}
$AppVersionInno = Format-InnoVersion "$AppVersion.$buildNumber"
$AppName = 'NiuMa'
$AppDescription = if ($pkgJson.description) { [string]$pkgJson.description } else { 'NiuMa Desktop' }
if (-not $Publisher) {
    $Publisher = if ($buildInfo.publisher) { [string]$buildInfo.publisher } else { 'NiuMa' }
}
if (-not $AppUrl) {
    $AppUrl = if ($buildInfo.homepage) { [string]$buildInfo.homepage } else { 'https://www.niuma007.com' }
}

$iscc = Find-InnoSetupCompiler
if (-not $iscc) {
    throw @"
Inno Setup compiler (ISCC.exe) not found.
Install (free for commercial use): winget install --id JRSoftware.InnoSetup -e
Then reopen the terminal and rerun: pnpm pack:win:setup
"@
}

$archLabel = if ($Arch -eq 'arm64') { 'arm64' } else { 'x64' }
$setupBaseName = "NiuMa-$AppVersion-windows-$archLabel-Setup"
$issWorkDir = Join-Path $Root 'build/pack-inno'
$issFile = Join-Path $issWorkDir 'niuma-setup.iss'
New-Item -ItemType Directory -Force -Path $issWorkDir | Out-Null
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$inputEscaped = Escape-InnoPath $InputDir
$outputEscaped = Escape-InnoPath $OutputDir
$iconPath = Join-Path $Root 'shell\resources\app.ico'
$iconLine = ''
if (Test-Path $iconPath) {
    $iconLine = "SetupIconFile=`"$((Escape-InnoPath $iconPath))`"`r`n"
}

$eulaZh = Join-Path $Root 'docs\legal\EULA.zh-CN.txt'
$eulaEn = Join-Path $Root 'docs\legal\EULA.en-US.txt'
if (-not (Test-Path $eulaZh) -or -not (Test-Path $eulaEn)) {
    throw "EULA missing under docs/legal/ (EULA.zh-CN.txt / EULA.en-US.txt)"
}
$eulaZhEscaped = Escape-InnoPath $eulaZh
$eulaEnEscaped = Escape-InnoPath $eulaEn
# Chocolatey 的 Inno 6.7 精简包不含 Languages\ChineseSimplified.isl，改用仓库内官方译文。
$zhIsl = Join-Path $PSScriptRoot 'languages\ChineseSimplified.isl'
if (-not (Test-Path $zhIsl)) {
    throw "ChineseSimplified.isl missing: $zhIsl"
}
$zhIslEscaped = Escape-InnoPath $zhIsl
$archAllowed = if ($Arch -eq 'arm64') { 'arm64' } else { 'x64compatible' }
$archInstallMode = if ($Arch -eq 'arm64') { 'arm64' } else { 'x64compatible' }

# 固定 AppId：升级安装必须保持不变。
# Inno 把 { } 当作常量，GUID 左花括号必须写成 {{ ，写入注册表后仍是 {GUID}。
$appId = '{{8F3C2A1B-4D5E-6F70-8A9B-0C1D2E3F4A5B}'

$issContent = @"
; Generated by scripts/platforms/windows/pack/build-installer.ps1 - do not edit by hand.
#define MyAppName "$AppName"
#define MyAppVersion "$AppVersionInno"
#define MyAppPublisher "$Publisher"
#define MyAppURL "$AppUrl"
#define MyAppExeName "niuma.exe"
#define SourceDir "$inputEscaped"
#define OutputDir "$outputEscaped"
#define OutputBase "$setupBaseName"

[Setup]
AppId=$appId
AppName={#MyAppName}
AppVersion=$AppVersion
AppVerName={#MyAppName} $AppVersion
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright=Copyright (C) {#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir={#OutputDir}
OutputBaseFilename={#OutputBase}
${iconLine}Compression=lzma2
SolidCompression=yes
WizardStyle=modern
SetupLogging=yes
MinVersion=10.0
SetupMutex=NiuMa.Desktop.Setup
UsePreviousAppDir=yes
UsePreviousLanguage=yes
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesAllowed=$archAllowed
ArchitecturesInstallIn64BitMode=$archInstallMode
DisableProgramGroupPage=yes
; 覆盖升级时关闭占用安装目录的进程，减少「文件正在使用」失败
CloseApplications=yes
RestartApplications=no
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoCopyright=Copyright (C) {#MyAppPublisher}
VersionInfoDescription=$AppDescription
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion=$AppVersion
; 静默安装：Setup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
; 仅当前用户：Setup.exe /CURRENTUSER（需配合 OverridesAllowed=dialog）

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "$eulaEnEscaped"
Name: "chinesesimplified"; MessagesFile: "$zhIslEscaped"; LicenseFile: "$eulaZhEscaped"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
"@

[System.IO.File]::WriteAllText($issFile, $issContent, [System.Text.UTF8Encoding]::new($false))

Write-Step "Inno Setup compile -> $OutputDir\$setupBaseName.exe"
& $iscc $issFile
if ($LASTEXITCODE -ne 0) {
    throw "ISCC failed ($LASTEXITCODE)"
}

$setupExe = Join-Path $OutputDir "$setupBaseName.exe"
if (-not (Test-Path $setupExe)) {
    throw "Installer not found after compile: $setupExe"
}

$SignScript = Join-Path $Root 'scripts\shared\sign\sign-windows.ps1'
if (Test-Path $SignScript) {
    & $SignScript -FilePath $setupExe
}

# 发版元数据：供 Admin 填写 download_url / sha256 / file_size
# GHA 精简 PowerShell 可能没有 Get-FileHash，改用 .NET SHA256。
$sha256 = Get-FileSha256Hex -Path $setupExe
$fileSize = (Get-Item -LiteralPath $setupExe).Length
$metaPath = Join-Path $OutputDir "$setupBaseName.release.json"
$channel = if ($buildInfo.channel) { [string]$buildInfo.channel } else { 'stable' }
$metaObj = [ordered]@{
    version      = $AppVersion
    channel      = $channel
    buildId      = [string]$buildInfo.buildId
    buildNumber  = $buildNumber
    platform     = 'windows'
    arch         = $Arch
    fileName     = (Split-Path -Leaf $setupExe)
    fileSize     = $fileSize
    sha256       = $sha256
    silentArgs   = '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'
    downloadHint = "上传 Setup 后把 HTTPS URL 写入 Admin；桌面默认允许 *.niuma007.com"
}
$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText(
    $metaPath,
    ($metaObj | ConvertTo-Json -Depth 4),
    $utf8
)

Write-Host "Installer ready: $setupExe" -ForegroundColor Green
Write-Host "sha256=$sha256" -ForegroundColor Cyan
Write-Host "file_size=$fileSize" -ForegroundColor Cyan
Write-Host "release meta: $metaPath" -ForegroundColor Cyan
Write-Output $setupExe
