/**
 * Oracle 表设计器草稿类型与工具函数。
 */

export type DataTypeParamKind = 'none' | 'length' | 'precision'

export interface OracleBaseTypeOption {
  base: string
  kind: DataTypeParamKind
  defaultLength?: number
  defaultPrecision?: number
  defaultScale?: number
}

/** Oracle 常用内建 / ANSI 同义类型（不含 MySQL 专有类型）。 */
export const ORACLE_BASE_TYPE_OPTIONS: OracleBaseTypeOption[] = [
  { base: 'NUMBER', kind: 'precision', defaultPrecision: 18, defaultScale: 2 },
  { base: 'INTEGER', kind: 'none' },
  { base: 'INT', kind: 'none' },
  { base: 'SMALLINT', kind: 'none' },
  { base: 'FLOAT', kind: 'length', defaultLength: 126 },
  { base: 'BINARY_FLOAT', kind: 'none' },
  { base: 'BINARY_DOUBLE', kind: 'none' },
  { base: 'VARCHAR2', kind: 'length', defaultLength: 255 },
  { base: 'NVARCHAR2', kind: 'length', defaultLength: 255 },
  { base: 'CHAR', kind: 'length', defaultLength: 1 },
  { base: 'NCHAR', kind: 'length', defaultLength: 1 },
  { base: 'RAW', kind: 'length', defaultLength: 16 },
  { base: 'CLOB', kind: 'none' },
  { base: 'NCLOB', kind: 'none' },
  { base: 'BLOB', kind: 'none' },
  { base: 'DATE', kind: 'none' },
  { base: 'TIMESTAMP', kind: 'length', defaultLength: 6 },
  { base: 'TIMESTAMP WITH TIME ZONE', kind: 'length', defaultLength: 6 },
  { base: 'TIMESTAMP WITH LOCAL TIME ZONE', kind: 'length', defaultLength: 6 },
  { base: 'INTERVAL YEAR TO MONTH', kind: 'none' },
  { base: 'INTERVAL DAY TO SECOND', kind: 'none' },
  { base: 'BOOLEAN', kind: 'none' },
  { base: 'JSON', kind: 'none' },
  { base: 'XMLTYPE', kind: 'none' },
  { base: 'ROWID', kind: 'none' },
  { base: 'UROWID', kind: 'length', defaultLength: 4000 },
]

/** @deprecated 使用 ORACLE_BASE_TYPE_OPTIONS */
export const ORACLE_BASE_TYPES: string[] = ORACLE_BASE_TYPE_OPTIONS.map((o) => o.base)

/** Oracle FK 仅支持 ON DELETE；无 RESTRICT / ON UPDATE。 */
export const ORACLE_FK_ACTIONS = ['NO ACTION', 'CASCADE', 'SET NULL', 'SET DEFAULT'] as const
export type OracleFkAction = (typeof ORACLE_FK_ACTIONS)[number]

/** Oracle 索引类型：普通 B-tree / 位图。 */
export const ORACLE_INDEX_METHODS = ['NORMAL', 'BITMAP'] as const
export type OracleIndexMethod = (typeof ORACLE_INDEX_METHODS)[number]

export interface ParsedDataType {
  base: string
  length?: number
  precision?: number
  scale?: number
  /** 字符型长度语义；BYTE 为库默认，不在字面量中输出。 */
  lengthSemantics?: 'CHAR'
  raw: string
}

export interface DesignColumnDraft {
  __rowKey: string
  originalName: string
  name: string
  /** 完整类型字面量，如 VARCHAR2(255)、NUMBER(18,2) */
  dataType: string
  typeBase: string
  typeLength?: number
  typeScale?: number
  /** 字符型为 CHAR 语义时保留，保存/预览时输出 VARCHAR2(n CHAR)。 */
  typeLengthSemantics?: 'CHAR'
  /** @deprecated Oracle 无 UNSIGNED；保留字段以免旧草稿崩溃 */
  unsigned: boolean
  /** @deprecated Oracle 无 ENUM；保留字段以免旧草稿崩溃 */
  enumValues: string
  nullable: boolean
  defaultExpr: string
  primaryKey: boolean
  /** 对应 GENERATED BY DEFAULT AS IDENTITY */
  autoIncrement: boolean
  comment: string
  removed: boolean
}

export interface DesignIndexDraft {
  __rowKey: string
  originalName: string
  name: string
  columnsText: string
  unique: boolean
  primary: boolean
  /** NORMAL / BITMAP */
  method: string
  removed: boolean
  snapName: string
  snapColumnsText: string
  snapUnique: boolean
  snapMethod: string
}

export interface DesignForeignKeyDraft {
  __rowKey: string
  originalName: string
  name: string
  columnsText: string
  refTable: string
  refColumnsText: string
  onDelete: string
  /** Oracle 不支持 ON UPDATE；保留字段仅作 UI 兼容 */
  onUpdate: string
  removed: boolean
}

let draftCounter = 0
export function nextDraftKey(prefix: string): string {
  return `${prefix}-${++draftCounter}`
}

export function resolveBaseTypeOption(base: string): OracleBaseTypeOption | undefined {
  const upper = base.trim().toUpperCase()
  return ORACLE_BASE_TYPE_OPTIONS.find((o) => o.base.toUpperCase() === upper)
}

export function dataTypeParamKind(base: string): DataTypeParamKind {
  return resolveBaseTypeOption(base)?.kind ?? 'none'
}

export function allowsUnsigned(_base: string): boolean {
  return false
}

export function newEmptyColumn(): DesignColumnDraft {
  return {
    __rowKey: nextDraftKey('col-new'),
    originalName: '',
    name: '',
    dataType: 'VARCHAR2(255)',
    typeBase: 'VARCHAR2',
    typeLength: 255,
    unsigned: false,
    enumValues: '',
    nullable: true,
    defaultExpr: '',
    primaryKey: false,
    autoIncrement: false,
    comment: '',
    removed: false,
  }
}

/** 新建表默认列：id NUMBER IDENTITY PRIMARY KEY。 */
export function defaultCreateTableColumns(): DesignColumnDraft[] {
  return [
    {
      __rowKey: nextDraftKey('col-id'),
      originalName: '',
      name: 'id',
      dataType: 'NUMBER',
      typeBase: 'NUMBER',
      unsigned: false,
      enumValues: '',
      nullable: false,
      defaultExpr: '',
      primaryKey: true,
      autoIncrement: true,
      comment: '',
      removed: false,
    },
  ]
}

export function newEmptyIndex(): DesignIndexDraft {
  return {
    __rowKey: nextDraftKey('idx-new'),
    originalName: '',
    name: '',
    columnsText: '',
    unique: false,
    primary: false,
    method: 'NORMAL',
    removed: false,
    snapName: '',
    snapColumnsText: '',
    snapUnique: false,
    snapMethod: 'NORMAL',
  }
}

export function newEmptyForeignKey(): DesignForeignKeyDraft {
  return {
    __rowKey: nextDraftKey('fk-new'),
    originalName: '',
    name: '',
    columnsText: '',
    refTable: '',
    refColumnsText: '',
    onDelete: 'NO ACTION',
    onUpdate: 'NO ACTION',
    removed: false,
  }
}

/** 解析 Oracle 类型字符串（支持多词类型 + 精度括号 + BYTE/CHAR 语义）。 */
const CHAR_LENGTH_BASES = new Set(['VARCHAR2', 'CHAR', 'NVARCHAR2', 'NCHAR'])

function supportsCharLengthSemantics(base: string): boolean {
  return CHAR_LENGTH_BASES.has(base.trim().toUpperCase())
}

export function parseDataType(raw: string): ParsedDataType {
  const trimmed = raw.trim().replace(/\s+/g, ' ')
  if (!trimmed) return { base: '', raw }

  const tsTz = trimmed.match(
    /^TIMESTAMP\s*\(\s*(\d+)\s*\)\s+(WITH\s+LOCAL\s+TIME\s+ZONE|WITH\s+TIME\s+ZONE)$/i,
  )
  if (tsTz) {
    const zone = tsTz[2].replace(/\s+/g, ' ').trim().toUpperCase()
    return {
      base: `TIMESTAMP ${zone}`,
      length: parseInt(tsTz[1], 10),
      raw,
    }
  }

  const charUnit = trimmed.match(/^(.+?)\s*\(\s*(\d+)\s+(BYTE|CHAR)\s*\)$/i)
  if (charUnit) {
    const base = charUnit[1].trim().toUpperCase()
    const unit = charUnit[3].toUpperCase()
    return {
      base,
      length: parseInt(charUnit[2], 10),
      lengthSemantics: unit === 'CHAR' ? 'CHAR' : undefined,
      raw,
    }
  }

  const paren = trimmed.match(/^(.+?)\s*\(\s*(\d+)(?:\s*,\s*(\d+))?\s*\)$/i)
  if (paren) {
    const base = paren[1].trim().toUpperCase()
    const first = parseInt(paren[2], 10)
    const second = paren[3] != null ? parseInt(paren[3], 10) : undefined
    if (second !== undefined) {
      return { base, precision: first, scale: second, raw }
    }
    return { base, length: first, raw }
  }

  return { base: trimmed.toUpperCase(), raw }
}

export function buildDataType(
  base: string,
  opts?: {
    length?: number
    scale?: number
    lengthSemantics?: 'CHAR'
  },
): string {
  const opt = resolveBaseTypeOption(base)
  const kind = opt?.kind ?? 'none'
  const core = base.trim().toUpperCase()

  if (kind === 'length' && opts?.length != null) {
    const charSuffix =
      opts.lengthSemantics === 'CHAR' && supportsCharLengthSemantics(core) ? ' CHAR' : ''
    return `${core}(${opts.length}${charSuffix})`
  }
  if (kind === 'precision' && opts?.length != null) {
    return opts.scale != null ? `${core}(${opts.length},${opts.scale})` : `${core}(${opts.length})`
  }
  return core
}

export function syncColumnDataType(col: Pick<
  DesignColumnDraft,
  'typeBase' | 'typeLength' | 'typeScale' | 'typeLengthSemantics'
>): string {
  return buildDataType(col.typeBase, {
    length: col.typeLength,
    scale: col.typeScale,
    lengthSemantics: col.typeLengthSemantics,
  })
}

export function splitDataTypeFields(raw: string): {
  dataType: string
  typeBase: string
  typeLength?: number
  typeScale?: number
  typeLengthSemantics?: 'CHAR'
  unsigned: boolean
  enumValues: string
} {
  const p = parseDataType(raw)
  const known = resolveBaseTypeOption(p.base)
  const typeBase = known?.base ?? p.base
  return {
    dataType: buildDataType(typeBase, {
      length: p.length ?? p.precision,
      scale: p.scale,
      lengthSemantics: p.lengthSemantics,
    }),
    typeBase,
    typeLength: p.length ?? p.precision,
    typeScale: p.scale,
    typeLengthSemantics: p.lengthSemantics,
    unsigned: false,
    enumValues: '',
  }
}

export function parseColumnList(text: string): string[] {
  return text
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
}

export function joinColumnList(cols: string[]): string {
  return cols.map((c) => c.trim()).filter(Boolean).join(', ')
}

export function suggestIndexName(columnsText: string, fallback = 'idx'): string {
  const cols = parseColumnList(columnsText)
  if (cols.length === 0) return fallback
  return `idx_${cols.join('_').slice(0, 48)}`
}

export function isDefaultIndexName(name: string): boolean {
  return !name.trim() || /^idx(_|$)/i.test(name.trim())
}

/** 已带引号 / 关键字 / 数字 / 函数的 DEFAULT，原样输出；其余按字符串字面量加单引号。 */
const ORACLE_DEFAULT_BARE_RE =
  /^(NULL|TRUE|FALSE|SYSDATE|SYSTIMESTAMP|CURRENT_DATE|CURRENT_TIMESTAMP(?:\(\d*\))?|LOCALTIMESTAMP(?:\(\d*\))?|USER|UID|SYS_GUID\(\))$/i
const ORACLE_DEFAULT_NUMBER_RE = /^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?$/

/**
 * 将 UI 中的默认值整理为可写入 DEFAULT 子句的 SQL 片段。
 */
export function formatOracleDefaultExpr(expr: string): string {
  const e = expr.trim()
  if (!e) return ''
  if (
    (e.startsWith("'") && e.endsWith("'")) ||
    (e.startsWith('"') && e.endsWith('"'))
  ) {
    return e
  }
  if (ORACLE_DEFAULT_BARE_RE.test(e)) return e
  if (ORACLE_DEFAULT_NUMBER_RE.test(e)) return e
  if (e.startsWith('(') && e.endsWith(')')) return e
  return `'${e.replace(/'/g, "''")}'`
}

export function columnsEqual(a: DesignColumnDraft, b: DesignColumnDraft): boolean {
  return (
    a.name === b.name &&
    a.dataType === b.dataType &&
    a.nullable === b.nullable &&
    a.defaultExpr === b.defaultExpr &&
    a.comment === b.comment &&
    a.autoIncrement === b.autoIncrement &&
    a.primaryKey === b.primaryKey
  )
}
