package ddl

import (
	"strings"
	"testing"
)

func TestPreviewCreateTableRejectsIdentityOnVarchar(t *testing.T) {
	t.Parallel()

	_, err := PreviewCreateTable(CreateTableParams{
		Schema: "public",
		Name:   "test",
		Columns: []CreateTableColumn{
			{
				Name:       "aqw",
				DataType:   "VARCHAR(20)",
				Nullable:   false,
				PrimaryKey: true,
				Identity:   "by_default",
			},
		},
	})
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "IDENTITY") {
		t.Fatalf("err=%v", err)
	}
}

func TestPreviewCreateTableIdentityOnBigint(t *testing.T) {
	t.Parallel()

	res, err := PreviewCreateTable(CreateTableParams{
		Schema: "public",
		Name:   "test",
		Columns: []CreateTableColumn{
			{
				Name:       "id",
				DataType:   "BIGINT",
				Nullable:   false,
				PrimaryKey: true,
				Identity:   "by_default",
			},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.SQL) == 0 || !strings.Contains(res.SQL[0], "GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("sql=%v", res.SQL)
	}
}
