package session

// queryCommand 描述一条 mongosh 查询补全项。
type queryCommand struct {
	Name        string
	Description string
	Body        string
	Kind        string
}

// shellHelpers 是 mongosh 顶层助手命令与 BSON 构造器。
var shellHelpers = []queryCommand{
	{Name: "show dbs", Description: "列出全部数据库", Body: "show dbs", Kind: "keyword"},
	{Name: "show databases", Description: "列出全部数据库", Body: "show databases", Kind: "keyword"},
	{Name: "show collections", Description: "列出当前库集合", Body: "show collections", Kind: "keyword"},
	{Name: "show tables", Description: "列出当前库集合（等同 show collections）", Body: "show tables", Kind: "keyword"},
	{Name: "show users", Description: "列出当前库用户", Body: "show users", Kind: "keyword"},
	{Name: "show roles", Description: "列出当前库角色", Body: "show roles", Kind: "keyword"},
	{Name: "show profile", Description: "显示最近的系统分析条目", Body: "show profile", Kind: "keyword"},
	{Name: "show logs", Description: "显示日志名称", Body: "show logs", Kind: "keyword"},
	{Name: "show log", Description: "显示指定日志", Body: "show log ${1:global}", Kind: "snippet"},
	{Name: "use", Description: "切换当前数据库", Body: "use ${1:database}", Kind: "snippet"},
	{Name: "db", Description: "当前数据库对象", Body: "db.", Kind: "keyword"},
	{Name: "help", Description: "显示帮助", Body: "help", Kind: "keyword"},
	{Name: "exit", Description: "退出 mongosh", Body: "exit", Kind: "keyword"},
	{Name: "ObjectId", Description: "构造 ObjectId", Body: "ObjectId('${1:hex}')", Kind: "function"},
	{Name: "ISODate", Description: "构造 ISO 日期", Body: "ISODate('${1:2024-01-01T00:00:00Z}')", Kind: "function"},
	{Name: "NumberLong", Description: "构造 64 位整数", Body: "NumberLong('${1:0}')", Kind: "function"},
	{Name: "NumberInt", Description: "构造 32 位整数", Body: "NumberInt(${1:0})", Kind: "function"},
	{Name: "NumberDecimal", Description: "构造 Decimal128", Body: "NumberDecimal('${1:0}')", Kind: "function"},
	{Name: "UUID", Description: "构造 UUID", Body: "UUID('${1:}')", Kind: "function"},
	{Name: "BinData", Description: "构造二进制数据", Body: "BinData(${1:0}, '${2:base64}')", Kind: "function"},
	{Name: "Timestamp", Description: "构造 Timestamp", Body: "Timestamp(${1:0}, ${2:0})", Kind: "function"},
	{Name: "MinKey", Description: "BSON MinKey", Body: "MinKey()", Kind: "function"},
	{Name: "MaxKey", Description: "BSON MaxKey", Body: "MaxKey()", Kind: "function"},
	{Name: "DBRef", Description: "构造 DBRef", Body: "DBRef('${1:collection}', ObjectId('${2:id}'))", Kind: "function"},
}

var dbMethods = []queryCommand{
	{Name: "getCollection", Description: "按名称获取集合句柄", Body: "getCollection('${1:collection}')", Kind: "function"},
	{Name: "getCollectionNames", Description: "列出当前库全部集合名", Body: "getCollectionNames()", Kind: "function"},
	{Name: "getCollectionInfos", Description: "列出当前库集合元信息", Body: "getCollectionInfos(${1:{}})", Kind: "function"},
	{Name: "getSiblingDB", Description: "切换到同连接下的其他数据库", Body: "getSiblingDB('${1:database}')", Kind: "function"},
	{Name: "getName", Description: "返回当前数据库名", Body: "getName()", Kind: "function"},
	{Name: "getMongo", Description: "返回连接对象", Body: "getMongo()", Kind: "function"},
	{Name: "runCommand", Description: "执行数据库命令", Body: "runCommand({ ${1:ping}: 1 })", Kind: "function"},
	{Name: "adminCommand", Description: "在 admin 库执行命令", Body: "adminCommand({ ${1:listDatabases}: 1 })", Kind: "function"},
	{Name: "stats", Description: "返回当前数据库统计信息", Body: "stats()", Kind: "function"},
	{Name: "version", Description: "返回服务器版本字符串", Body: "version()", Kind: "function"},
	{Name: "serverStatus", Description: "服务器状态摘要", Body: "serverStatus()", Kind: "function"},
	{Name: "hostInfo", Description: "主机信息", Body: "hostInfo()", Kind: "function"},
	{Name: "currentOp", Description: "当前操作列表", Body: "currentOp()", Kind: "function"},
	{Name: "killOp", Description: "终止操作", Body: "killOp(${1:opid})", Kind: "function"},
	{Name: "createCollection", Description: "创建集合", Body: "createCollection('${1:collection}')", Kind: "function"},
	{Name: "createView", Description: "创建视图", Body: "createView('${1:view}', '${2:source}', [${3:}])", Kind: "function"},
	{Name: "dropDatabase", Description: "删除当前数据库", Body: "dropDatabase()", Kind: "function"},
	{Name: "dropAllUsers", Description: "删除当前库全部用户", Body: "dropAllUsers()", Kind: "function"},
	{Name: "auth", Description: "认证", Body: "auth('${1:user}', '${2:password}')", Kind: "function"},
	{Name: "logout", Description: "注销当前认证", Body: "logout()", Kind: "function"},
	{Name: "createUser", Description: "创建用户", Body: "createUser({ user: '${1:user}', pwd: '${2:password}', roles: [${3:}] })", Kind: "function"},
	{Name: "updateUser", Description: "更新用户", Body: "updateUser('${1:user}', { ${2:} })", Kind: "function"},
	{Name: "changeUserPassword", Description: "修改用户密码", Body: "changeUserPassword('${1:user}', '${2:password}')", Kind: "function"},
	{Name: "dropUser", Description: "删除用户", Body: "dropUser('${1:user}')", Kind: "function"},
	{Name: "getUsers", Description: "列出用户", Body: "getUsers()", Kind: "function"},
	{Name: "getRoles", Description: "列出角色", Body: "getRoles()", Kind: "function"},
	{Name: "createRole", Description: "创建角色", Body: "createRole({ role: '${1:role}', privileges: [], roles: [] })", Kind: "function"},
	{Name: "dropRole", Description: "删除角色", Body: "dropRole('${1:role}')", Kind: "function"},
	{Name: "setLogLevel", Description: "设置日志级别", Body: "setLogLevel(${1:1})", Kind: "function"},
	{Name: "setProfilingLevel", Description: "设置分析级别", Body: "setProfilingLevel(${1:1}, { slowms: ${2:100} })", Kind: "function"},
	{Name: "getProfilingStatus", Description: "获取分析状态", Body: "getProfilingStatus()", Kind: "function"},
	{Name: "fsyncLock", Description: "锁定写入以进行备份", Body: "fsyncLock()", Kind: "function"},
	{Name: "fsyncUnlock", Description: "解除 fsync 锁", Body: "fsyncUnlock()", Kind: "function"},
	{Name: "printCollectionStats", Description: "打印集合统计", Body: "printCollectionStats()", Kind: "function"},
	{Name: "printShardingStatus", Description: "打印分片状态", Body: "printShardingStatus()", Kind: "function"},
	{Name: "hello", Description: "副本集/拓扑 hello", Body: "hello()", Kind: "function"},
	{Name: "isMaster", Description: "isMaster（兼容）", Body: "isMaster()", Kind: "function"},
}

var collectionMethods = []queryCommand{
	{Name: "find", Description: "查询匹配文档", Body: "find(${1:{}})", Kind: "function"},
	{Name: "findOne", Description: "查询单条文档", Body: "findOne(${1:{}})", Kind: "function"},
	{Name: "findOneAndUpdate", Description: "查找并更新单条", Body: "findOneAndUpdate(${1:{}}, { $set: { ${2:} } }, ${3:{ returnDocument: 'after' }})", Kind: "function"},
	{Name: "findOneAndReplace", Description: "查找并替换单条", Body: "findOneAndReplace(${1:{}}, ${2:{}}, ${3:{ returnDocument: 'after' }})", Kind: "function"},
	{Name: "findOneAndDelete", Description: "查找并删除单条", Body: "findOneAndDelete(${1:{}})", Kind: "function"},
	{Name: "aggregate", Description: "执行聚合管道", Body: "aggregate([\n  { $match: ${1:{}} },\n  { $limit: 20 }\n])", Kind: "function"},
	{Name: "countDocuments", Description: "统计匹配文档数", Body: "countDocuments(${1:{}})", Kind: "function"},
	{Name: "estimatedDocumentCount", Description: "估算集合文档总数", Body: "estimatedDocumentCount()", Kind: "function"},
	{Name: "distinct", Description: "返回字段唯一值", Body: "distinct('${1:field}', ${2:{}})", Kind: "function"},
	{Name: "insertOne", Description: "插入单条文档", Body: "insertOne(${1:{}})", Kind: "function"},
	{Name: "insertMany", Description: "批量插入文档", Body: "insertMany([${1:{}}], ${2:{ ordered: true }})", Kind: "function"},
	{Name: "updateOne", Description: "更新单条文档", Body: "updateOne(${1:{}}, { $set: { ${2:} } })", Kind: "function"},
	{Name: "updateMany", Description: "批量更新文档", Body: "updateMany(${1:{}}, { $set: { ${2:} } })", Kind: "function"},
	{Name: "replaceOne", Description: "替换单条文档", Body: "replaceOne(${1:{}}, ${2:{}})", Kind: "function"},
	{Name: "deleteOne", Description: "删除单条文档", Body: "deleteOne(${1:{}})", Kind: "function"},
	{Name: "deleteMany", Description: "批量删除文档", Body: "deleteMany(${1:{}})", Kind: "function"},
	{Name: "bulkWrite", Description: "批量写操作", Body: "bulkWrite([\n  { insertOne: { document: ${1:{}} } }\n])", Kind: "function"},
	{Name: "createIndex", Description: "创建索引", Body: "createIndex({ ${1:field}: 1 })", Kind: "function"},
	{Name: "createIndexes", Description: "批量创建索引", Body: "createIndexes([{ key: { ${1:field}: 1 } }])", Kind: "function"},
	{Name: "getIndexes", Description: "列出集合索引", Body: "getIndexes()", Kind: "function"},
	{Name: "dropIndex", Description: "删除指定索引", Body: "dropIndex('${1:indexName}')", Kind: "function"},
	{Name: "dropIndexes", Description: "删除全部索引", Body: "dropIndexes()", Kind: "function"},
	{Name: "hideIndex", Description: "隐藏索引", Body: "hideIndex('${1:indexName}')", Kind: "function"},
	{Name: "unhideIndex", Description: "取消隐藏索引", Body: "unhideIndex('${1:indexName}')", Kind: "function"},
	{Name: "reIndex", Description: "重建索引", Body: "reIndex()", Kind: "function"},
	{Name: "drop", Description: "删除集合", Body: "drop()", Kind: "function"},
	{Name: "renameCollection", Description: "重命名集合", Body: "renameCollection('${1:newName}')", Kind: "function"},
	{Name: "stats", Description: "集合统计", Body: "stats()", Kind: "function"},
	{Name: "dataSize", Description: "数据大小（字节）", Body: "dataSize()", Kind: "function"},
	{Name: "storageSize", Description: "存储大小（字节）", Body: "storageSize()", Kind: "function"},
	{Name: "totalIndexSize", Description: "索引总大小", Body: "totalIndexSize()", Kind: "function"},
	{Name: "totalSize", Description: "总大小", Body: "totalSize()", Kind: "function"},
	{Name: "validate", Description: "校验集合", Body: "validate({ full: ${1|false,true|} })", Kind: "function"},
	{Name: "isCapped", Description: "是否为 capped 集合", Body: "isCapped()", Kind: "function"},
	{Name: "watch", Description: "Change Stream 监听", Body: "watch([${1:}])", Kind: "function"},
	{Name: "explain", Description: "解释计划（无游标时）", Body: "explain('${1|queryPlanner,executionStats|}')", Kind: "function"},
	{Name: "getShardDistribution", Description: "分片数据分布", Body: "getShardDistribution()", Kind: "function"},
	{Name: "getShardVersion", Description: "分片版本", Body: "getShardVersion()", Kind: "function"},
	{Name: "exists", Description: "集合是否存在", Body: "exists()", Kind: "function"},
	{Name: "getDB", Description: "所属数据库对象", Body: "getDB()", Kind: "function"},
	{Name: "getFullName", Description: "完整命名空间", Body: "getFullName()", Kind: "function"},
	{Name: "getName", Description: "集合名", Body: "getName()", Kind: "function"},
	{Name: "latencyStats", Description: "延迟统计", Body: "latencyStats()", Kind: "function"},
}

var cursorChainMethods = []queryCommand{
	{Name: "limit", Description: "限制返回文档数", Body: "limit(${1:20})", Kind: "function"},
	{Name: "skip", Description: "跳过指定数量文档", Body: "skip(${1:0})", Kind: "function"},
	{Name: "sort", Description: "按字段排序", Body: "sort({ ${1:field}: ${2|-1,1|} })", Kind: "function"},
	{Name: "project", Description: "选择输出字段", Body: "project({ ${1:field}: 1 })", Kind: "function"},
	{Name: "projection", Description: "选择输出字段（别名）", Body: "projection({ ${1:field}: 1 })", Kind: "function"},
	{Name: "hint", Description: "指定查询索引", Body: "hint({ ${1:field}: 1 })", Kind: "function"},
	{Name: "maxTimeMS", Description: "设置最大执行时间（毫秒）", Body: "maxTimeMS(${1:3000})", Kind: "function"},
	{Name: "batchSize", Description: "设置游标批次大小", Body: "batchSize(${1:100})", Kind: "function"},
	{Name: "collation", Description: "排序规则", Body: "collation({ locale: '${1:en}', strength: ${2:1} })", Kind: "function"},
	{Name: "comment", Description: "为查询添加注释", Body: "comment('${1:}')", Kind: "function"},
	{Name: "allowDiskUse", Description: "允许磁盘临时文件", Body: "allowDiskUse(${1|true,false|})", Kind: "function"},
	{Name: "readConcern", Description: "读关注", Body: "readConcern('${1|local,majority,available,linearizable,snapshot|}')", Kind: "function"},
	{Name: "readPref", Description: "读偏好", Body: "readPref('${1|primary,primaryPreferred,secondary,secondaryPreferred,nearest|}')", Kind: "function"},
	{Name: "returnKey", Description: "仅返回索引键", Body: "returnKey(${1|true,false|})", Kind: "function"},
	{Name: "showRecordId", Description: "显示记录 ID", Body: "showRecordId(${1|true,false|})", Kind: "function"},
	{Name: "noCursorTimeout", Description: "禁用游标超时", Body: "noCursorTimeout(${1|true,false|})", Kind: "function"},
	{Name: "tailable", Description: "tailable 游标", Body: "tailable(${1|true,false|})", Kind: "function"},
	{Name: "awaitData", Description: "tailable 等待新数据", Body: "awaitData(${1|true,false|})", Kind: "function"},
	{Name: "toArray", Description: "将游标结果转为数组", Body: "toArray()", Kind: "function"},
	{Name: "forEach", Description: "遍历游标", Body: "forEach(doc => { ${1:printjson(doc)} })", Kind: "function"},
	{Name: "map", Description: "映射游标", Body: "map(doc => ${1:doc})", Kind: "function"},
	{Name: "itcount", Description: "迭代并计数", Body: "itcount()", Kind: "function"},
	{Name: "pretty", Description: "美化输出（shell）", Body: "pretty()", Kind: "function"},
	{Name: "explain", Description: "返回查询执行计划", Body: "explain('${1|queryPlanner,executionStats,allPlansExecution|}')", Kind: "function"},
	{Name: "max", Description: "索引上界", Body: "max({ ${1:field}: ${2:} })", Kind: "function"},
	{Name: "min", Description: "索引下界", Body: "min({ ${1:field}: ${2:} })", Kind: "function"},
	{Name: "objsLeftInBatch", Description: "当前批次剩余文档数", Body: "objsLeftInBatch()", Kind: "function"},
	{Name: "hasNext", Description: "是否还有下一文档", Body: "hasNext()", Kind: "function"},
	{Name: "next", Description: "取下一文档", Body: "next()", Kind: "function"},
	{Name: "close", Description: "关闭游标", Body: "close()", Kind: "function"},
	{Name: "isClosed", Description: "游标是否已关闭", Body: "isClosed()", Kind: "function"},
	{Name: "isExhausted", Description: "游标是否已耗尽", Body: "isExhausted()", Kind: "function"},
}

// shellQueryOperators 供 find/filter 对象内补全（较聚合 queryOperators 更全）。
var shellQueryOperators = []queryCommand{
	{Name: "$and", Description: "逻辑与", Body: "$and: [ ${1:{}} ]", Kind: "snippet"},
	{Name: "$or", Description: "逻辑或", Body: "$or: [ ${1:{}} ]", Kind: "snippet"},
	{Name: "$nor", Description: "逻辑非或", Body: "$nor: [ ${1:{}} ]", Kind: "snippet"},
	{Name: "$not", Description: "逻辑非", Body: "$not: { ${1:} }", Kind: "snippet"},
	{Name: "$expr", Description: "聚合表达式查询", Body: "$expr: { ${1:} }", Kind: "snippet"},
	{Name: "$eq", Description: "等于", Body: "$eq: ${1:value}", Kind: "snippet"},
	{Name: "$ne", Description: "不等于", Body: "$ne: ${1:value}", Kind: "snippet"},
	{Name: "$gt", Description: "大于", Body: "$gt: ${1:value}", Kind: "snippet"},
	{Name: "$gte", Description: "大于等于", Body: "$gte: ${1:value}", Kind: "snippet"},
	{Name: "$lt", Description: "小于", Body: "$lt: ${1:value}", Kind: "snippet"},
	{Name: "$lte", Description: "小于等于", Body: "$lte: ${1:value}", Kind: "snippet"},
	{Name: "$in", Description: "属于数组", Body: "$in: [ ${1:value} ]", Kind: "snippet"},
	{Name: "$nin", Description: "不属于数组", Body: "$nin: [ ${1:value} ]", Kind: "snippet"},
	{Name: "$exists", Description: "字段是否存在", Body: "$exists: ${1|true,false|}", Kind: "snippet"},
	{Name: "$type", Description: "BSON 类型", Body: "$type: '${1:string}'", Kind: "snippet"},
	{Name: "$regex", Description: "正则匹配", Body: "$regex: '${1:}', $options: '${2:i}'", Kind: "snippet"},
	{Name: "$options", Description: "正则选项", Body: "$options: '${1:i}'", Kind: "snippet"},
	{Name: "$elemMatch", Description: "数组元素匹配", Body: "$elemMatch: { ${1:} }", Kind: "snippet"},
	{Name: "$size", Description: "数组长度", Body: "$size: ${1:1}", Kind: "snippet"},
	{Name: "$all", Description: "包含全部元素", Body: "$all: [ ${1:} ]", Kind: "snippet"},
	{Name: "$mod", Description: "取模", Body: "$mod: [ ${1:2}, ${2:0} ]", Kind: "snippet"},
	{Name: "$text", Description: "文本搜索", Body: "$text: { $search: '${1:}' }", Kind: "snippet"},
	{Name: "$where", Description: "JS 表达式（慎用）", Body: "$where: '${1:this.x > 0}'", Kind: "snippet"},
	{Name: "$jsonSchema", Description: "JSON Schema 校验", Body: "$jsonSchema: { ${1:} }", Kind: "snippet"},
	{Name: "$bitsAllClear", Description: "位全部为 0", Body: "$bitsAllClear: ${1:}", Kind: "snippet"},
	{Name: "$bitsAllSet", Description: "位全部为 1", Body: "$bitsAllSet: ${1:}", Kind: "snippet"},
	{Name: "$bitsAnyClear", Description: "任一位为 0", Body: "$bitsAnyClear: ${1:}", Kind: "snippet"},
	{Name: "$bitsAnySet", Description: "任一位为 1", Body: "$bitsAnySet: ${1:}", Kind: "snippet"},
	{Name: "$geoWithin", Description: "地理位置范围内", Body: "$geoWithin: { $geometry: ${1:} }", Kind: "snippet"},
	{Name: "$geoIntersects", Description: "地理相交", Body: "$geoIntersects: { $geometry: ${1:} }", Kind: "snippet"},
	{Name: "$near", Description: "附近点", Body: "$near: { $geometry: ${1:}, $maxDistance: ${2:1000} }", Kind: "snippet"},
	{Name: "$nearSphere", Description: "球面附近点", Body: "$nearSphere: { $geometry: ${1:}, $maxDistance: ${2:1000} }", Kind: "snippet"},
	{Name: "$slice", Description: "投影数组切片", Body: "$slice: ${1:5}", Kind: "snippet"},
	{Name: "$meta", Description: "元数据投影", Body: "$meta: '${1:textScore}'", Kind: "snippet"},
	{Name: "$set", Description: "更新：设置字段", Body: "$set: { ${1:field}: ${2:value} }", Kind: "snippet"},
	{Name: "$unset", Description: "更新：删除字段", Body: "$unset: { ${1:field}: '' }", Kind: "snippet"},
	{Name: "$inc", Description: "更新：数值增减", Body: "$inc: { ${1:field}: ${2:1} }", Kind: "snippet"},
	{Name: "$push", Description: "更新：追加数组", Body: "$push: { ${1:field}: ${2:} }", Kind: "snippet"},
	{Name: "$pull", Description: "更新：移除数组元素", Body: "$pull: { ${1:field}: ${2:} }", Kind: "snippet"},
	{Name: "$addToSet", Description: "更新：集合式追加", Body: "$addToSet: { ${1:field}: ${2:} }", Kind: "snippet"},
	{Name: "$currentDate", Description: "更新：当前时间", Body: "$currentDate: { ${1:field}: true }", Kind: "snippet"},
}
