import { defineHostTheme } from '../types'

export const lantaiThemeId = 'niuma.lantai' as const

/** 兰台：报表大屏。深底、青辉、金线。终端色与界面同一套。 */
export const lantaiTheme = defineHostTheme({
  id: lantaiThemeId,
  label: 'Lantai',
  labelKey: 'settings.themeLantai',
  icon: 'layout-dashboard',
  legacyIds: ['report'] as readonly string[],
  uiTheme: 'dark',
  colors: {
    primary: '#3ec6ff',
    primaryHover: '#7ad7ff',
    primaryForeground: '#041018',
    primaryContainer: '#123044',
    onPrimaryContainer: '#d6f4ff',
    bg: '#070d18',
    surface: '#0e1728',
    surfaceElevated: '#152238',
    surfaceHover: '#1c2d4a',
    itemHover: '#1c2d4a',
    inputBg: '#0b1322',
    inputBorder: '#2a4368',
    inputBorderHover: '#3d6a9a',
    border: '#2a4368',
    borderSubtle: '#1c3050',
    text: '#e7f2ff',
    muted: '#93a8c4',
    placeholder: '#6d82a0',
    textDisabled: '#516480',
    textInverse: '#070d18',
    danger: '#ff6b81',
    dangerContainer: '#3a1a24',
    onDangerContainer: '#ffd0d8',
    success: '#3dd68c',
    successContainer: '#123328',
    onSuccessContainer: '#c8f5df',
    warning: '#f5c451',
    warningContainer: '#3a2e12',
    onWarningContainer: '#ffe7b0',
    info: '#3ec6ff',
    infoContainer: '#123044',
    onInfoContainer: '#d6f4ff',
  },
  tokens: {
    '--nm-aurora-a': '#3ec6ff',
    '--nm-aurora-b': '#6d7cff',
    '--nm-aurora-c': '#f5c451',
    '--nm-aurora-d': '#3dd68c',
    '--nm-aurora-e': '#7a5cff',
    '--nm-on-aurora': '#f4fbff',
    '--nm-aurora-opacity': '0.42',
    '--nm-glass-bg': '#0e1728',
    '--nm-glass-blur': '12px',
    '--nm-elev-highlight': 'rgb(62 198 255 / 10%)',
    '--nm-elev-shadow': '0 24px 60px rgb(0 0 0 / 50%)',
    '--nm-editor-glow': 'radial-gradient(closest-side, rgb(62 198 255 / 18%), transparent 72%)',
    '--nm-letter-spacing': '0',
    '--nm-activity-explorer': '#3ec6ff',
    '--nm-activity-data': '#7a5cff',
    '--nm-activity-ops': '#f5c451',
    '--nm-activity-devtools': '#3dd68c',
    '--rs-radius-xs': '0.125rem',
    '--rs-radius-sm': '0.25rem',
    '--rs-radius': '0.25rem',
    '--rs-radius-lg': '0.375rem',
    '--rs-terminal-shell-bg': '#050910',
    '--rs-terminal-bg': '#0a1220',
    '--rs-terminal-fg': '#d7e8ff',
    '--rs-terminal-cursor': '#3ec6ff',
    '--rs-terminal-cursor-accent': '#0a1220',
    '--rs-terminal-row-stripe': '#101a2c',
    '--rs-terminal-selection-bg': '#16405c',
    '--rs-terminal-selection-fg': '#f4fbff',
    '--rs-terminal-border': '#1c3050',
    '--rs-terminal-ansi-black': '#070d18',
    '--rs-terminal-ansi-red': '#ff6b81',
    '--rs-terminal-ansi-green': '#3dd68c',
    '--rs-terminal-ansi-yellow': '#f5c451',
    '--rs-terminal-ansi-blue': '#3ec6ff',
    '--rs-terminal-ansi-magenta': '#7a5cff',
    '--rs-terminal-ansi-cyan': '#5ee0d0',
    '--rs-terminal-ansi-white': '#c5d4ea',
    '--rs-terminal-ansi-bright-black': '#516480',
    '--rs-terminal-ansi-bright-red': '#ff9aab',
    '--rs-terminal-ansi-bright-green': '#7aebb4',
    '--rs-terminal-ansi-bright-yellow': '#ffe08a',
    '--rs-terminal-ansi-bright-blue': '#8ad8ff',
    '--rs-terminal-ansi-bright-magenta': '#b09cff',
    '--rs-terminal-ansi-bright-cyan': '#9af0e4',
    '--rs-terminal-ansi-bright-white': '#f4fbff',
  },
})
