import { defineHostTheme } from '../types'

export const wuxiaThemeId = 'niuma.wuxia' as const

/** 武侠风：墨底、朱砂、泥金。终端色与界面同一套。 */
export const wuxiaTheme = defineHostTheme({
  id: wuxiaThemeId,
  label: 'Wuxia',
  labelKey: 'settings.themeWuxia',
  icon: 'swords',
  uiTheme: 'dark',
  colors: {
    primary: '#c23b2e',
    primaryHover: '#d85a48',
    primaryForeground: '#f8f1e3',
    primaryContainer: '#3a1c18',
    onPrimaryContainer: '#f3d2c4',
    bg: '#12100e',
    surface: '#1c1814',
    surfaceElevated: '#262019',
    surfaceHover: '#322a22',
    itemHover: '#322a22',
    inputBg: '#161310',
    inputBorder: '#4a3d32',
    inputBorderHover: '#6e5a48',
    border: '#4a3d32',
    borderSubtle: '#322a22',
    text: '#f3e6c8',
    muted: '#b5a48c',
    placeholder: '#8a7b68',
    textDisabled: '#6a5d4e',
    textInverse: '#12100e',
    danger: '#e15a4a',
    dangerContainer: '#3d1e1a',
    onDangerContainer: '#f6c7bf',
    success: '#7d9a6a',
    successContainer: '#243024',
    onSuccessContainer: '#d5e6c8',
    warning: '#d4a24a',
    warningContainer: '#3a2e16',
    onWarningContainer: '#f3e0b0',
    info: '#c6a15b',
    infoContainer: '#3a3018',
    onInfoContainer: '#f3e6c4',
  },
  tokens: {
    '--nm-aurora-a': '#c23b2e',
    '--nm-aurora-b': '#c6a15b',
    '--nm-aurora-c': '#6e2b3c',
    '--nm-aurora-d': '#d8c7a1',
    '--nm-aurora-e': '#7d9a6a',
    '--nm-on-aurora': '#f8f1e3',
    '--nm-aurora-opacity': '0.45',
    '--nm-glass-bg': '#1c1814',
    '--nm-glass-blur': '16px',
    '--nm-elev-highlight': 'rgb(243 230 200 / 8%)',
    '--nm-elev-shadow': '0 24px 60px rgb(0 0 0 / 46%)',
    '--nm-editor-glow': 'radial-gradient(closest-side, rgb(194 59 46 / 22%), transparent 72%)',
    '--nm-letter-spacing': '0.01em',
    '--nm-activity-explorer': '#c6a15b',
    '--nm-activity-data': '#c23b2e',
    '--nm-activity-ops': '#7d9a6a',
    '--nm-activity-devtools': '#d4a24a',
    '--rs-radius-xs': '0.25rem',
    '--rs-radius-sm': '0.375rem',
    '--rs-radius': '0.5rem',
    '--rs-radius-lg': '0.75rem',
    '--rs-terminal-shell-bg': '#0e0c0a',
    '--rs-terminal-bg': '#16130f',
    '--rs-terminal-fg': '#f3e6c8',
    '--rs-terminal-cursor': '#c23b2e',
    '--rs-terminal-cursor-accent': '#16130f',
    '--rs-terminal-row-stripe': '#1e1a15',
    '--rs-terminal-selection-bg': '#5a2a24',
    '--rs-terminal-selection-fg': '#f8f1e3',
    '--rs-terminal-border': '#3a3028',
    '--rs-terminal-ansi-black': '#1a1612',
    '--rs-terminal-ansi-red': '#e15a4a',
    '--rs-terminal-ansi-green': '#7d9a6a',
    '--rs-terminal-ansi-yellow': '#d4a24a',
    '--rs-terminal-ansi-blue': '#7f93b0',
    '--rs-terminal-ansi-magenta': '#b87a9a',
    '--rs-terminal-ansi-cyan': '#7a9a8a',
    '--rs-terminal-ansi-white': '#e6d7bc',
    '--rs-terminal-ansi-bright-black': '#6a5d4e',
    '--rs-terminal-ansi-bright-red': '#f09080',
    '--rs-terminal-ansi-bright-green': '#a8c496',
    '--rs-terminal-ansi-bright-yellow': '#f0d090',
    '--rs-terminal-ansi-bright-blue': '#a8bdd4',
    '--rs-terminal-ansi-bright-magenta': '#e0a8b4',
    '--rs-terminal-ansi-bright-cyan': '#c4d4b0',
    '--rs-terminal-ansi-bright-white': '#fff8ee',
  },
})
