import { defineHostTheme } from '../types'

export const yuegongThemeId = 'niuma.yuegong' as const

/** 月宫：内容区是冷岩白，边栏略沉一档。字是岩墨。终端与界面同一套。 */
export const yuegongTheme = defineHostTheme({
  id: yuegongThemeId,
  label: 'Yuegong',
  labelKey: 'settings.themeYuegong',
  icon: 'moon-star',
  uiTheme: 'light',
  colors: {
    primary: '#3e4c5c',
    primaryHover: '#2f3b48',
    primaryForeground: '#f4f7f9',
    primaryContainer: '#d7e1ea',
    onPrimaryContainer: '#1c242c',
    bg: '#d7e0e8',
    surface: '#eef2f5',
    surfaceElevated: '#f7f9fb',
    surfaceHover: '#e2e8ee',
    itemHover: '#e2e8ee',
    inputBg: '#f7f9fb',
    inputBorder: '#c5ced6',
    inputBorderHover: '#8e9aaa',
    border: '#c5ced6',
    borderSubtle: '#dde4ea',
    text: '#1c242c',
    muted: '#5c6772',
    placeholder: '#8a94a0',
    textDisabled: '#a8b2bc',
    textInverse: '#f4f7f9',
    danger: '#c4473e',
    dangerContainer: '#f8e4e1',
    onDangerContainer: '#6e241e',
    success: '#2f7a5a',
    successContainer: '#e3f2ea',
    onSuccessContainer: '#1a4a34',
    warning: '#9a7040',
    warningContainer: '#f6ecd8',
    onWarningContainer: '#5c4018',
    info: '#3e4c5c',
    infoContainer: '#d7e1ea',
    onInfoContainer: '#1c242c',
  },
  tokens: {
    '--nm-aurora-a': '#e8eef3',
    '--nm-aurora-b': '#d7e0e8',
    '--nm-aurora-c': '#c5ced6',
    '--nm-aurora-d': '#f4f7f9',
    '--nm-aurora-e': '#9aa8b5',
    '--nm-on-aurora': '#1c242c',
    '--nm-aurora-opacity': '0.28',
    '--nm-glass-bg': '#f4f7f9',
    '--nm-glass-blur': '20px',
    '--nm-elev-highlight': 'rgb(255 255 255 / 72%)',
    '--nm-elev-shadow': '0 24px 60px rgb(28 36 44 / 12%)',
    '--nm-editor-glow': 'radial-gradient(closest-side, rgb(232 238 243 / 70%), transparent 72%)',
    '--nm-letter-spacing': '0.02em',
    '--nm-activity-explorer': '#3e4c5c',
    '--nm-activity-data': '#6a7c8e',
    '--nm-activity-ops': '#9a7040',
    '--nm-activity-devtools': '#3d7a62',
    '--rs-radius-xs': '0.375rem',
    '--rs-radius-sm': '0.5rem',
    '--rs-radius': '0.75rem',
    '--rs-radius-lg': '1rem',
    '--rs-terminal-shell-bg': '#d7e0e8',
    '--rs-terminal-bg': '#e8eef3',
    '--rs-terminal-fg': '#1c242c',
    '--rs-terminal-cursor': '#3e4c5c',
    '--rs-terminal-cursor-accent': '#e8eef3',
    '--rs-terminal-row-stripe': '#e2e8ee',
    '--rs-terminal-selection-bg': '#c5d0da',
    '--rs-terminal-selection-fg': '#1c242c',
    '--rs-terminal-border': '#c5ced6',
    '--rs-terminal-ansi-black': '#1c242c',
    '--rs-terminal-ansi-red': '#c4473e',
    '--rs-terminal-ansi-green': '#2f7a5a',
    '--rs-terminal-ansi-yellow': '#9a7040',
    '--rs-terminal-ansi-blue': '#3e4c5c',
    '--rs-terminal-ansi-magenta': '#6e5a78',
    '--rs-terminal-ansi-cyan': '#3d6e72',
    '--rs-terminal-ansi-white': '#d7dee6',
    '--rs-terminal-ansi-bright-black': '#5c6772',
    '--rs-terminal-ansi-bright-red': '#e07a72',
    '--rs-terminal-ansi-bright-green': '#5a9a78',
    '--rs-terminal-ansi-bright-yellow': '#c4a06a',
    '--rs-terminal-ansi-bright-blue': '#6a7c8e',
    '--rs-terminal-ansi-bright-magenta': '#8a7896',
    '--rs-terminal-ansi-bright-cyan': '#5a9094',
    '--rs-terminal-ansi-bright-white': '#f4f7f9',
  },
})
